import { Ingredient, RarityKey, RarityInfo, IngredientGenre, IngredientGenreInfo } from "@/types";

export const RARITY: Record<RarityKey, RarityInfo> = {
  common:    { label: "コモン",       star: 1, color: "#9CA3AF", icon: "⭐" },
  uncommon:  { label: "アンコモン",   star: 2, color: "#4CAF50", icon: "⭐" },
  rare:      { label: "レア",         star: 3, color: "#E91E8C", icon: "⭐" },
  legendary: { label: "レジェンダリー", star: 4, color: "#F59E0B", icon: "⭐" },
};

export const INGREDIENT_GENRES: IngredientGenreInfo[] = [
  { key: "water",      label: "うるおい",     icon: "💧", color: "#4FC3F7" },
  { key: "amino_acid", label: "アミノ酸",     icon: "🧬", color: "#7986CB" },
  { key: "vitamin",    label: "ビタミン",     icon: "🍊", color: "#FFB74D" },
  { key: "peptide",    label: "ペプチド",     icon: "🧪", color: "#E91E8C" },
  { key: "botanical",  label: "ボタニカル",   icon: "🌿", color: "#4CAF50" },
  { key: "oil_lipid",  label: "オイル・脂質", icon: "🫧", color: "#81C784" },
  { key: "ferment",    label: "発酵・バイオ", icon: "🧫", color: "#9C27B0" },
  { key: "acid",       label: "アシッド",     icon: "⚗️", color: "#90A4AE" },
  { key: "base",       label: "ベース",       icon: "⚙️", color: "#BDBDBD" },
];

export function getGenreInfo(key: IngredientGenre): IngredientGenreInfo | undefined {
  return INGREDIENT_GENRES.find(g => g.key === key);
}

/** ジャンル別の解説テキスト */
export const GENRE_DESCRIPTIONS: Record<IngredientGenre, { summary: string; detail: string }> = {
  water: {
    summary: "化粧品のベースとなる水分系の保湿成分",
    detail: "ヒアルロン酸やグリセリンなど、水分を抱え込んで肌にうるおいを届ける成分群です。ほぼすべてのスキンケア製品に配合されている、最も基本的で大切な成分たちです。",
  },
  amino_acid: {
    summary: "肌の天然保湿因子（NMF）を構成する基本成分",
    detail: "アミノ酸は肌のうるおいを保つNMFの約40%を占めます。セリン、グリシン、アルギニンなど個々は地味ですが、複数のアミノ酸が組み合わさることで高い保湿力を発揮します。",
  },
  vitamin: {
    summary: "肌を整え、守り、ハリを与えるビタミン類",
    detail: "ビタミンC誘導体（整肌）、レチノール（ハリ）、ビタミンE（保護）など、スキンケアの主役級の成分が揃うジャンルです。種類によって働きが大きく異なるため、目的に合わせた選び方が大切です。",
  },
  peptide: {
    summary: "アミノ酸が結合した高機能シグナル成分",
    detail: "ペプチドはアミノ酸が数個〜数十個つながった成分で、肌にシグナルを送ってコラーゲンやエラスチンの産生をサポートします。EGFやFGFなどの成長因子もこのジャンルに含まれます。",
  },
  botanical: {
    summary: "植物のちからを活かした天然由来の成分",
    detail: "ツボクサ（CICA）、カミツレ、ドクダミなど、古くから薬草として使われてきた植物由来の成分です。鎮静・整肌・保湿など多彩なはたらきを持ち、肌にやさしいイメージで人気があります。",
  },
  oil_lipid: {
    summary: "肌のバリアを守る油分・脂質系の成分",
    detail: "セラミド、スクワラン、シア脂など、肌表面にうるおいのヴェールを作り、水分の蒸発を防ぐ成分群です。乾燥肌やバリア機能が気になる方には特に重要なジャンルです。",
  },
  ferment: {
    summary: "微生物の発酵パワーを活かしたバイオ成分",
    detail: "ガラクトミセス培養液やビフィズス菌溶解質など、酵母や乳酸菌を発酵させて得られる成分です。肌のバリア機能や常在菌バランスをサポートし、韓国コスメで特に注目されています。",
  },
  acid: {
    summary: "角質をやさしくケアする酸系の成分",
    detail: "AHA（グリコール酸・乳酸）、BHA（サリチル酸）、PHA（グルコノラクトン）など、古い角質をおだやかに取り除く成分です。使用後は紫外線対策をしっかり行うことが大切です。",
  },
  base: {
    summary: "製品の品質を保つ縁の下の力持ち",
    detail: "防腐剤、乳化剤、pH調整剤、紫外線防止剤など、製品の安定性や使用感を支える成分です。華やかさはありませんが、安全に化粧品を使うために欠かせない重要な存在です。",
  },
};

export const MASTER_INGREDIENTS: Ingredient[] = [
  // ─── 整肌系 ───────────────────────────────────────────────
  {
    id: "niacinamide",
    nameJa: "ナイアシンアミド",
    nameInci: "Niacinamide",
    categories: ["brightening", "barrier", "moisturizing"],
    rarity: "common",
    genre: "vitamin",
    color: "#CE93D8",
    note: "ビタミンB3の一種で、多くのスキンケア製品に配合される成分です。",
    funFact: "ビタミンB3は水溶性ビタミンで、体内で補酵素NADの前駆体として働きます。",
  },
  {
    id: "arbutin",
    nameJa: "アルブチン",
    nameInci: "Arbutin",
    categories: ["brightening"],
    rarity: "rare",
    genre: "botanical",
    color: "#7C6AE8",
    note: "コケモモなどに含まれる整肌系の成分です。",
    funFact: "1989年に日本で医薬部外品の有効成分として承認されました。",
  },
  {
    id: "alpha-arbutin",
    nameJa: "α-アルブチン",
    nameInci: "Alpha-Arbutin",
    categories: ["brightening"],
    rarity: "rare",
    genre: "botanical",
    color: "#7C6AE8",
    note: "通常のアルブチンより安定性が高く、整肌系成分として注目されています。",
    funFact: "α型はβ型（アルブチン）と比べて安定性・効果が高いとされています。",
  },
  {
    id: "tranexamic-acid",
    nameJa: "トラネキサム酸",
    nameInci: "Tranexamic Acid",
    categories: ["brightening", "soothing"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "医薬品として使われてきた成分で、整肌・鎮静系として化粧品にも配合されます。",
    funFact: "もともと止血剤として開発されましたが、肌への作用も発見されました。",
  },
  {
    id: "ascorbic-acid",
    nameJa: "アスコルビン酸",
    nameInci: "Ascorbic Acid",
    categories: ["brightening", "turnover"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#CE93D8",
    note: "ビタミンCそのもので、整肌系・ハリ系に分類される成分です。",
    funFact: "壊血病の予防として発見された歴史があります。",
    caution: "酸化しやすいため、保存方法に注意が必要な成分です。",
  },
  {
    id: "ascorbyl-glucoside",
    nameJa: "アスコルビルグルコシド",
    nameInci: "Ascorbyl Glucoside",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#CE93D8",
    note: "ビタミンCにグルコースを結合させた安定型ビタミンC誘導体です。",
    funFact: "水に溶けやすく酸化しにくいため、扱いやすいビタミンC誘導体です。",
  },
  {
    id: "ethyl-ascorbic-acid",
    nameJa: "3-O-エチルアスコルビン酸",
    nameInci: "3-O-Ethyl Ascorbic Acid",
    categories: ["brightening"],
    rarity: "rare",
    genre: "vitamin",
    color: "#CE93D8",
    note: "高い安定性と浸透性を持つビタミンC誘導体です。",
    funFact: "油溶性と水溶性の両方の性質を持つ両親媒性の成分です。",
  },
  {
    id: "sodium-ascorbyl-phosphate",
    nameJa: "アスコルビルリン酸Na",
    nameInci: "Sodium Ascorbyl Phosphate",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#CE93D8",
    note: "水溶性の安定型ビタミンC誘導体で、幅広い製品に配合されます。",
  },
  {
    id: "tocopherol",
    nameJa: "トコフェロール",
    nameInci: "Tocopherol",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#CE93D8",
    note: "ビタミンEの一種で、整肌系に分類される成分です。",
    funFact: "「子供を産む」を意味するギリシャ語が名前の由来です。",
  },
  {
    id: "kojic-acid",
    nameJa: "コウジ酸",
    nameInci: "Kojic Acid",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "麹菌が産生する有機酸で、日本酒の醸造過程で発見された整肌成分です。",
    funFact: "麹（こうじ）からその名が付いています。",
  },
  {
    id: "astaxanthin",
    nameJa: "アスタキサンチン",
    nameInci: "Astaxanthin",
    categories: ["brightening", "barrier"],
    rarity: "legendary",
    genre: "vitamin",
    color: "#F59E0B",
    note: "カロテノイドの一種で、整肌・バリア系に分類される希少成分です。",
    funFact: "サケやエビの赤色の元となる天然色素です。",
  },
  {
    id: "fullerene",
    nameJa: "フラーレン",
    nameInci: "Fullerene",
    categories: ["brightening"],
    rarity: "legendary",
    genre: "ferment",
    color: "#F59E0B",
    note: "炭素原子60個で構成される球状分子で、高い整肌機能を持つ希少成分です。",
    funFact: "1985年に発見され、発見者はノーベル化学賞を受賞しました。",
  },
  {
    id: "resveratrol",
    nameJa: "レスベラトロール",
    nameInci: "Resveratrol",
    categories: ["brightening", "soothing"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "赤ワインやブドウの皮に含まれるポリフェノールの一種です。",
    funFact: "フランスのパラドックスを説明する成分として研究が進みました。",
  },
  {
    id: "ubiquinone",
    nameJa: "ユビキノン",
    nameInci: "Ubiquinone",
    categories: ["brightening"],
    rarity: "rare",
    genre: "vitamin",
    color: "#CE93D8",
    note: "CoQ10（コエンザイムQ10）とも呼ばれる整肌系成分です。",
    funFact: "細胞のエネルギー産生に関わる補酵素として体内にも存在します。",
  },

  // ─── ハリ・弾力系 ─────────────────────────────────────────
  {
    id: "retinol",
    nameJa: "レチノール",
    nameInci: "Retinol",
    categories: ["turnover"],
    rarity: "rare",
    genre: "vitamin",
    color: "#FFB74D",
    note: "ビタミンAの一種で、ハリ・弾力系に分類される成分です。",
    funFact: "レチノールは1909年に発見された最初のビタミンです。",
    caution: "光に不安定なため、夜間の使用が一般的です。使い始めは少量からが推奨されます。",
  },
  {
    id: "retinal",
    nameJa: "レチナール",
    nameInci: "Retinal",
    categories: ["turnover"],
    rarity: "legendary",
    genre: "vitamin",
    color: "#F59E0B",
    note: "レチノールよりも1段階変換が少ない高活性型ビタミンA誘導体です。",
    funFact: "目の網膜（retina）にも存在し、光を感知する役割を持ちます。",
    caution: "高い活性を持つため、使い始めは低濃度・低頻度から始めることが推奨されます。",
  },
  {
    id: "retinyl-palmitate",
    nameJa: "レチニルパルミテート",
    nameInci: "Retinyl Palmitate",
    categories: ["turnover"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#FFB74D",
    note: "パルミチン酸とレチノールのエステルで、比較的穏やかなビタミンA誘導体です。",
    funFact: "食品にも使われる安全性の高いビタミンA誘導体の一つです。",
  },
  {
    id: "hydroxypinacolone-retinoate",
    nameJa: "ヒドロキシピナコロンレチノエート",
    nameInci: "Hydroxypinacolone Retinoate",
    categories: ["turnover"],
    rarity: "rare",
    genre: "vitamin",
    color: "#FFB74D",
    note: "レチノイド系のビタミンA誘導体として、スキンケアで注目されている成分です。",
    funFact: "比較的新しいレチノイド系成分として紹介されることがありますが、化粧品での知見はまだ限定的です。",
  },
  {
    id: "bakuchiol",
    nameJa: "バクチオール",
    nameInci: "Bakuchiol",
    categories: ["turnover"],
    rarity: "rare",
    genre: "vitamin",
    color: "#FFB74D",
    note: "植物由来のハリ・弾力系成分で、レチノールの代替として注目されています。",
    funFact: "インドの伝統医学アーユルヴェーダで古くから使われてきた植物由来です。",
  },
  {
    id: "peptide",
    nameJa: "ペプチド",
    nameInci: "Palmitoyl Tripeptide-1",
    categories: ["turnover", "barrier"],
    rarity: "legendary",
    genre: "peptide",
    color: "#F59E0B",
    note: "アミノ酸が結合した成分で、ハリ・弾力系・バリア系に分類される希少成分です。",
    funFact: "ペプチドは「消化する」を意味するギリシャ語が語源です。",
  },
  {
    id: "acetyl-hexapeptide-3",
    nameJa: "アセチルヘキサペプチド-3",
    nameInci: "Acetyl Hexapeptide-3",
    categories: ["turnover"],
    rarity: "legendary",
    genre: "peptide",
    color: "#F59E0B",
    note: "アルジレリンとも呼ばれる6つのアミノ酸からなるペプチド成分です。",
    funFact: "神経伝達物質の作用に着目して開発されたペプチドです。",
  },
  {
    id: "copper-tripeptide-1",
    nameJa: "銅トリペプチド-1",
    nameInci: "Copper Tripeptide-1",
    categories: ["turnover", "barrier"],
    rarity: "legendary",
    genre: "peptide",
    color: "#F59E0B",
    note: "銅イオンと3つのアミノ酸が結合したペプチドで、ハリ・バリア系の希少成分です。",
    funFact: "1970年代に血漿中で発見された生体由来のペプチドです。",
  },
  {
    id: "adenosine",
    nameJa: "アデノシン",
    nameInci: "Adenosine",
    categories: ["turnover"],
    rarity: "rare",
    genre: "acid",
    color: "#FFB74D",
    note: "細胞のエネルギー通貨ATPの構成成分で、ハリ・弾力系成分として配合されます。",
    funFact: "韓国食品医薬品安全処（MFDS）で機能性成分として認可されています。",
  },
  {
    id: "hydrolyzed-collagen",
    nameJa: "加水分解コラーゲン",
    nameInci: "Hydrolyzed Collagen",
    categories: ["moisturizing", "turnover"],
    rarity: "uncommon",
    genre: "peptide",
    color: "#4FC3F7",
    note: "コラーゲンを加水分解して低分子化した保湿・ハリ系成分です。",
    funFact: "肌の真皮層の約70%はコラーゲンで構成されています。",
  },
  {
    id: "hydrolyzed-elastin",
    nameJa: "加水分解エラスチン",
    nameInci: "Hydrolyzed Elastin",
    categories: ["moisturizing", "turnover"],
    rarity: "uncommon",
    genre: "peptide",
    color: "#4FC3F7",
    note: "エラスチンを加水分解した保湿・弾力系成分です。",
    funFact: "エラスチンはゴムのような弾性を持ち、肌の弾力を支えています。",
  },

  // ─── 保湿系 ────────────────────────────────────────────────
  {
    id: "sodium-hyaluronate",
    nameJa: "ヒアルロン酸Na",
    nameInci: "Sodium Hyaluronate",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "高い保水力を持つ保湿成分として広く知られています。",
    funFact: "1gで約6リットルの水分を保持できると言われています。",
  },
  {
    id: "acetylated-hyaluronate",
    nameJa: "アセチル化ヒアルロン酸Na",
    nameInci: "Sodium Acetylated Hyaluronate",
    categories: ["moisturizing"],
    rarity: "rare",
    genre: "water",
    color: "#4FC3F7",
    note: "通常のヒアルロン酸Naよりも油溶性が高まり、肌表面に留まりやすい高機能保湿成分です。",
    funFact: "スーパーヒアルロン酸と呼ばれることがあり、しっとりした使用感を狙って配合されます。",
  },
  {
    id: "hydrolyzed-hyaluronate",
    nameJa: "加水分解ヒアルロン酸",
    nameInci: "Hydrolyzed Hyaluronic Acid",
    categories: ["moisturizing"],
    rarity: "uncommon",
    genre: "water",
    color: "#4FC3F7",
    note: "ヒアルロン酸を加水分解して低分子化した保湿成分です。",
    funFact: "分子が小さいため肌深部への浸透性が高いとされています。",
  },
  {
    id: "sodium-polyglutamate",
    nameJa: "ポリグルタミン酸Na",
    nameInci: "Sodium Polyglutamate",
    categories: ["moisturizing"],
    rarity: "uncommon",
    genre: "water",
    color: "#4FC3F7",
    note: "納豆の糸に含まれる天然のポリアミノ酸で、高い保湿力を持ちます。",
    funFact: "納豆菌が産生するネバネバの成分がこのポリグルタミン酸です。",
  },
  {
    id: "glycerin",
    nameJa: "グリセリン",
    nameInci: "Glycerin",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "最も基本的な保湿成分の一つで、多くの化粧品に配合されています。",
    funFact: "食品にも使われる安全性の高い成分です。",
  },
  {
    id: "bg",
    nameJa: "BG",
    nameInci: "Butylene Glycol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "ブチレングリコールとも呼ばれる保湿・溶剤成分で、ほぼすべての化粧品に配合されます。",
    funFact: "保湿だけでなく防腐補助剤としても機能します。",
  },
  {
    id: "pentylene-glycol",
    nameJa: "ペンチレングリコール",
    nameInci: "Pentylene Glycol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "植物由来の保湿成分で、防腐補助効果も持ちます。",
    funFact: "天然のサトウキビなどから得られる成分です。",
  },
  {
    id: "diglycerin",
    nameJa: "ジグリセリン",
    nameInci: "Diglycerin",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "グリセリンが2分子結合した保湿成分で、グリセリンより粘度が低いです。",
  },
  {
    id: "sorbitol",
    nameJa: "ソルビトール",
    nameInci: "Sorbitol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "果物に含まれる天然の糖アルコールで、穏やかな保湿作用があります。",
    funFact: "リンゴやナシなどの果物に天然に含まれています。",
  },
  {
    id: "trehalose",
    nameJa: "トレハロース",
    nameInci: "Trehalose",
    categories: ["moisturizing"],
    rarity: "uncommon",
    genre: "water",
    color: "#4FC3F7",
    note: "2分子のグルコースからなる二糖類の保湿成分です。",
    funFact: "乾燥に強い生物（クマムシ等）が体内に蓄える糖として知られています。",
  },
  {
    id: "betaine",
    nameJa: "ベタイン",
    nameInci: "Betaine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "砂糖大根に含まれる天然の保湿成分で、肌をしっとりさせます。",
    funFact: "テンサイ（砂糖大根）から発見された成分で、「ビート」が名前の由来です。",
  },
  {
    id: "squalane",
    nameJa: "スクワラン",
    nameInci: "Squalane",
    categories: ["moisturizing", "barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "もともと人の皮脂にも含まれる成分で、なじみの良いオイル成分です。",
    funFact: "かつてはサメの肝油から得られていましたが、現在は植物由来が主流です。",
  },
  {
    id: "shea-butter",
    nameJa: "シア脂",
    nameInci: "Butyrospermum Parkii Butter",
    categories: ["moisturizing", "barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "アフリカ産シアの木の実から得られる天然の植物性バターです。",
    funFact: "西アフリカでは「生命の木」と呼ばれ、何世紀も使われてきた成分です。",
  },
  {
    id: "jojoba-oil",
    nameJa: "ホホバ種子油",
    nameInci: "Simmondsia Chinensis Seed Oil",
    categories: ["moisturizing", "barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "ホホバの種子から得られる植物性ワックスエステルで、人の皮脂に近い成分です。",
    funFact: "植物油ではなくワックスエステルに分類され、酸化しにくい特性があります。",
  },
  {
    id: "caprylic-capric-triglyceride",
    nameJa: "カプリル酸/カプリン酸トリグリセリル",
    nameInci: "Caprylic/Capric Triglyceride",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#4FC3F7",
    note: "ヤシ油・パーム核油由来のエモリエント成分で、のびの良いテクスチャーを与えます。",
    funFact: "MCTオイルとも呼ばれ、食品としても使われます。",
  },
  {
    id: "dimethicone",
    nameJa: "ジメチコン",
    nameInci: "Dimethicone",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#9CA3AF",
    note: "シリコーン系のエモリエント成分で、なめらかさとのびの良さを与えます。",
    funFact: "シリコーン樹脂の一種で、医療機器にも使われるほど安全性が高い成分です。",
  },
  {
    id: "cetyl-alcohol",
    nameJa: "セタノール",
    nameInci: "Cetyl Alcohol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#9CA3AF",
    note: "高級アルコールの一種で、エモリエント・乳化補助として配合されます。",
    funFact: "名前に「アルコール」とありますが、肌を乾燥させるアルコールとは別の成分です。",
  },
  {
    id: "stearyl-alcohol",
    nameJa: "ステアリルアルコール",
    nameInci: "Stearyl Alcohol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#9CA3AF",
    note: "高級脂肪アルコールで、クリームやローションの質感調整に使われます。",
  },
  {
    id: "cetearyl-alcohol",
    nameJa: "セテアリルアルコール",
    nameInci: "Cetearyl Alcohol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#9CA3AF",
    note: "セタノールとステアリルアルコールの混合物で、乳化・エモリエントに使われます。",
  },
  {
    id: "isopropyl-myristate",
    nameJa: "ミリスチン酸イソプロピル",
    nameInci: "Isopropyl Myristate",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#9CA3AF",
    note: "軽いテクスチャーのエモリエント成分で、のびの良さを与えます。",
  },
  {
    id: "aloe-vera",
    nameJa: "アロエベラ液汁",
    nameInci: "Aloe Barbadensis Leaf Juice",
    categories: ["moisturizing", "soothing"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "アロエベラの葉から得られる液汁で、保湿成分として使われることがあります。",
    funFact: "古くからスキンケア素材として知られ、古代エジプトの文献にも登場します。",
  },
  {
    id: "panthenol",
    nameJa: "パンテノール",
    nameInci: "Panthenol",
    categories: ["moisturizing", "soothing"],
    rarity: "common",
    genre: "vitamin",
    color: "#80CBC4",
    note: "プロビタミンB5とも呼ばれ、保湿・鎮静効果を持つ汎用性の高い成分です。",
    funFact: "皮膚でパントテン酸（ビタミンB5）に変換されます。",
  },
  {
    id: "polyquaternium-51",
    nameJa: "ポリクオタニウム-51",
    nameInci: "Polyquaternium-51",
    categories: ["moisturizing", "barrier"],
    rarity: "rare",
    genre: "peptide",
    color: "#4FC3F7",
    note: "細胞膜に似た構造を持つ擬似セラミド型の保湿成分です。",
    funFact: "「リピジュア」の商品名でも知られる、日本発の成分です。",
  },
  {
    id: "hydrolyzed-silk",
    nameJa: "加水分解シルク",
    nameInci: "Hydrolyzed Silk",
    categories: ["moisturizing"],
    rarity: "rare",
    genre: "peptide",
    color: "#4FC3F7",
    note: "シルクを加水分解したタンパク質成分で、なめらかさと保湿効果を与えます。",
    funFact: "シルクはセリシンとフィブロインという2種類のタンパク質でできています。",
  },
  {
    id: "arginine",
    nameJa: "アルギニン",
    nameInci: "Arginine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "アミノ酸の一種で、保湿と肌コンディショニングに役立ちます。",
    funFact: "ヒトの体内で合成される半必須アミノ酸です。",
  },
  {
    id: "glycine",
    nameJa: "グリシン",
    nameInci: "Glycine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "最もシンプルなアミノ酸で、保湿成分として配合されます。",
    funFact: "コラーゲンの約3分の1がグリシン残基で構成されています。",
  },
  {
    id: "serine",
    nameJa: "セリン",
    nameInci: "Serine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "天然保湿因子（NMF）の構成成分の一つであるアミノ酸です。",
    funFact: "NMFの約18%を占めるアミノ酸成分です。",
  },
  {
    id: "proline",
    nameJa: "プロリン",
    nameInci: "Proline",
    categories: ["moisturizing", "turnover"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "コラーゲンに多く含まれるアミノ酸で、保湿とハリ系の両面に関わります。",
    funFact: "コラーゲンの約13%がプロリン残基で構成されています。",
  },

  // ─── バリア系 ──────────────────────────────────────────────
  {
    id: "ceramide-np",
    nameJa: "セラミドNP",
    nameInci: "Ceramide NP",
    categories: ["barrier", "moisturizing"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種です。",
    funFact: "ヒトの角質層に存在する細胞間脂質の主成分です。",
  },
  {
    id: "ceramide-eop",
    nameJa: "セラミドEOP",
    nameInci: "Ceramide EOP",
    categories: ["barrier"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種で、長鎖脂肪酸を持ちます。",
    funFact: "セラミドEOPは「E」がエステル型、「O」がオレイン酸、「P」がフィトスフィンゴシン骨格を意味します。",
  },
  {
    id: "ceramide-ap",
    nameJa: "セラミドAP",
    nameInci: "Ceramide AP",
    categories: ["barrier"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種です。",
  },
  {
    id: "ceramide-eos",
    nameJa: "セラミドEOS",
    nameInci: "Ceramide EOS",
    categories: ["barrier"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種です。",
  },
  {
    id: "ceramide-ng",
    nameJa: "セラミドNG",
    nameInci: "Ceramide NG",
    categories: ["barrier"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種で、バリア系の保湿製品で見かけることがあります。",
  },
  {
    id: "phytosphingosine",
    nameJa: "フィトスフィンゴシン",
    nameInci: "Phytosphingosine",
    categories: ["barrier", "soothing"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "セラミドの前駆体となるスフィンゴイド塩基で、バリア系成分として知られています。",
    funFact: "酵母から発酵生産される天然由来の成分です。",
  },
  {
    id: "cholesterol",
    nameJa: "コレステロール",
    nameInci: "Cholesterol",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "肌の細胞間脂質の構成成分の一つで、セラミドとともにバリア機能を担います。",
    funFact: "皮膚のバリア機能にはセラミド・コレステロール・脂肪酸の3成分が重要です。",
  },
  {
    id: "cica",
    nameJa: "CICA",
    nameInci: "Centella Asiatica",
    categories: ["soothing", "barrier"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "ツボクサ由来の成分で、鎮静・バリア系に分類されます。",
    funFact: "韓国スキンケアブームで世界的に注目された成分です。",
  },
  {
    id: "centella-asiatica-extract",
    nameJa: "ツボクサエキス",
    nameInci: "Centella Asiatica Extract",
    categories: ["soothing", "barrier"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "ツボクサから得られるエキスで、整肌・バリア系に分類されることがある成分です。",
    funFact: "アジア圏の伝統医学で古くから傷の治癒に使われてきた植物です。",
  },

  // ─── 鎮静系 ────────────────────────────────────────────────
  {
    id: "allantoin",
    nameJa: "アラントイン",
    nameInci: "Allantoin",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "肌荒れ防止に分類される鎮静系の成分です。",
    funFact: "コンフリー（ヒレハリソウ）の根から発見された成分です。",
  },
  {
    id: "dipotassium-glycyrrhizate",
    nameJa: "グリチルリチン酸2K",
    nameInci: "Dipotassium Glycyrrhizate",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "甘草に含まれる成分で、医薬部外品の有効成分にも指定されている鎮静成分です。",
    funFact: "甘草は漢方でも広く使われ、その甘味成分がグリチルリチン酸です。",
  },
  {
    id: "stearyl-glycyrrhetinate",
    nameJa: "グリチルレチン酸ステアリル",
    nameInci: "Stearyl Glycyrrhetinate",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "グリチルリチン酸の誘導体で、油溶性の鎮静成分です。",
    funFact: "医薬部外品の有効成分として認められている成分です。",
  },
  {
    id: "bisabolol",
    nameJa: "ビサボロール",
    nameInci: "Bisabolol",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "カモミールに含まれるテルペン系アルコールで、整肌目的で配合されることがあります。",
    funFact: "ドイツカモミールの精油成分として発見されました。",
  },
  {
    id: "azulene",
    nameJa: "アズレン",
    nameInci: "Azulene",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "カモミールから得られる深い青色の鎮静成分です。",
    funFact: "その鮮やかな青色から「アズール（空色）」という名前が付いています。",
  },
  {
    id: "chamomilla-extract",
    nameJa: "カミツレ花エキス",
    nameInci: "Chamomilla Recutita Flower Extract",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "カモミールの花から得られるエキスで、保湿・整肌目的で使われます。",
    funFact: "ハーブティーとしても有名なカモミールは数千年の使用歴史があります。",
  },
  {
    id: "green-tea-extract",
    nameJa: "チャ葉エキス",
    nameInci: "Camellia Sinensis Leaf Extract",
    categories: ["soothing", "brightening"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "緑茶から得られるポリフェノール豊富なエキスで、整肌目的で使われます。",
    funFact: "緑茶のカテキンは強い抗酸化作用を持つことで知られています。",
  },
  {
    id: "oat-extract",
    nameJa: "エンバクエキス",
    nameInci: "Avena Sativa Kernel Extract",
    categories: ["soothing", "moisturizing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "オートミールの原料であるエンバク（オーツ麦）から得られるエキスです。",
    funFact: "FDA（米国食品医薬品局）がスキンケア成分として認可したオート麦成分です。",
  },
  {
    id: "houttuynia-cordata-extract",
    nameJa: "ドクダミエキス",
    nameInci: "Houttuynia Cordata Extract",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "ドクダミから得られるエキスで、古くから民間療法で使われてきた鎮静成分です。",
    funFact: "日本の伝統的な薬草で「十薬」とも呼ばれています。",
  },
  {
    id: "caffeine",
    nameJa: "カフェイン",
    nameInci: "Caffeine",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#90A4AE",
    note: "コーヒーや茶葉に含まれるアルカロイドで、スキンケアでは鎮静・引き締め目的で使われます。",
    funFact: "目の周りの浮腫を抑えるアイクリームに多く配合されています。",
  },

  // ─── 角質ケア系 ──────────────────────────────────────────
  {
    id: "salicylic-acid",
    nameJa: "サリチル酸",
    nameInci: "Salicylic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "BHA（β-ヒドロキシ酸）に分類される角質ケア成分です。",
    funFact: "ヤナギの樹皮から発見された歴史ある成分です。",
    caution: "濃度や使用頻度によっては刺激を感じる場合があります。",
  },
  {
    id: "glycolic-acid",
    nameJa: "グリコール酸",
    nameInci: "Glycolic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "AHA（α-ヒドロキシ酸）の中で最も分子が小さく、浸透性の高い角質ケア成分です。",
    funFact: "サトウキビから得られる天然由来の成分です。",
    caution: "使用後は紫外線対策をしっかり行うことが推奨されます。",
  },
  {
    id: "lactic-acid",
    nameJa: "乳酸",
    nameInci: "Lactic Acid",
    categories: ["keratin", "moisturizing"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "AHAの一種で、角質ケアと保湿の両面に作用する成分です。",
    funFact: "ヨーグルトや発酵乳製品に含まれる天然成分です。",
    caution: "AHA共通の注意として、使用後は日焼け対策が重要です。",
  },
  {
    id: "mandelic-acid",
    nameJa: "マンデル酸",
    nameInci: "Mandelic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "AHAの中で最も分子が大きく、比較的穏やかな角質ケア成分です。",
    funFact: "苦扁桃（ビターアーモンド）から最初に得られました。",
  },
  {
    id: "gluconolactone",
    nameJa: "グルコノラクトン",
    nameInci: "Gluconolactone",
    categories: ["keratin", "moisturizing"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "PHA（ポリヒドロキシ酸）の一種で、AHAより穏やかな角質ケア・保湿成分です。",
    funFact: "AHAよりも分子が大きいため、刺激が少ないとされています。",
  },
  {
    id: "lactobionic-acid",
    nameJa: "ラクトビオン酸",
    nameInci: "Lactobionic Acid",
    categories: ["keratin", "moisturizing"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "PHA（ポリヒドロキシ酸）の一種で、保湿力の高い穏やかな角質ケア成分です。",
    funFact: "乳糖を酸化して得られる成分で、高い吸湿性を持ちます。",
  },
  {
    id: "citric-acid",
    nameJa: "クエン酸",
    nameInci: "Citric Acid",
    categories: ["keratin"],
    rarity: "common",
    genre: "acid",
    color: "#90A4AE",
    note: "AHAの一種で、pH調整や軽い角質ケア目的で多くの化粧品に配合されます。",
    funFact: "レモンなどの柑橘類に多く含まれる有機酸です。",
  },
  {
    id: "malic-acid",
    nameJa: "リンゴ酸",
    nameInci: "Malic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "リンゴに多く含まれるAHAの一種で、穏やかな角質ケア効果があります。",
    funFact: "「リンゴ酸」の名前の通りリンゴから発見された成分です。",
  },

  // ─── 植物油・バリア強化 ───────────────────────────────────
  {
    id: "rosehip-oil",
    nameJa: "ローズヒップ油",
    nameInci: "Rosa Canina Fruit Oil",
    categories: ["barrier", "brightening"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "バラの実から得られるオイルで、脂肪酸とビタミンCを豊富に含みます。",
    funFact: "チリやアルゼンチンの先住民族が古くから傷の治療に使ってきた成分です。",
  },
  {
    id: "argan-oil",
    nameJa: "アルガニアスピノサ核油",
    nameInci: "Argania Spinosa Kernel Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "モロッコのアルガンの木の実から得られる「液体ゴールド」とも呼ばれるオイルです。",
    funFact: "アルガンの木はモロッコにしか生息せず、ユネスコの生物圏保護区に指定されています。",
  },
  {
    id: "olive-oil",
    nameJa: "オリーブ果実油",
    nameInci: "Olea Europaea Fruit Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "地中海原産のオリーブから得られる植物油で、肌のバリア機能を助けます。",
    funFact: "食用・化粧用・医薬用として数千年の使用歴史があります。",
  },
  {
    id: "sunflower-seed-oil",
    nameJa: "ヒマワリ種子油",
    nameInci: "Helianthus Annuus Seed Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "ひまわりの種子から得られる軽いテクスチャーの植物油です。",
    funFact: "リノール酸が豊富で肌のバリア機能のサポートに役立ちます。",
  },
  {
    id: "macadamia-oil",
    nameJa: "マカデミア種子油",
    nameInci: "Macadamia Integrifolia Seed Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "マカダミアナッツから得られる植物油で、パルミトレイン酸が豊富です。",
    funFact: "人の皮脂に含まれるパルミトレイン酸と組成が似ています。",
  },
  {
    id: "rice-bran-oil",
    nameJa: "コメヌカ油",
    nameInci: "Oryza Sativa Bran Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "米ぬかから得られる植物油で、γ-オリザノールなどの有用成分を含みます。",
    funFact: "日本古来より美容オイルとして使われてきた成分です。",
  },

  // ─── 防腐・基剤・乳化 ─────────────────────────────────────
  {
    id: "phenoxyethanol",
    nameJa: "フェノキシエタノール",
    nameInci: "Phenoxyethanol",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "防腐剤として広く使用される成分です。",
    funFact: "緑茶にも微量に含まれる天然由来の成分です。",
  },
  {
    id: "methylparaben",
    nameJa: "メチルパラベン",
    nameInci: "Methylparaben",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "最も一般的なパラベン系防腐剤で、低濃度での使用が認められています。",
    funFact: "ブルーベリーなどの果物にも微量に天然に含まれています。",
  },
  {
    id: "ethylparaben",
    nameJa: "エチルパラベン",
    nameInci: "Ethylparaben",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "パラベン系防腐剤の一種で、広く化粧品に使用されます。",
  },
  {
    id: "propylparaben",
    nameJa: "プロピルパラベン",
    nameInci: "Propylparaben",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "パラベン系防腐剤の一種で、メチルパラベンと組み合わせて使用されます。",
  },
  {
    id: "butylparaben",
    nameJa: "ブチルパラベン",
    nameInci: "Butylparaben",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "パラベン系防腐剤の一種で、油溶性が高い特徴があります。",
  },
  {
    id: "carbomer",
    nameJa: "カルボマー",
    nameInci: "Carbomer",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "増粘剤・ゲル化剤として使用される高分子成分です。",
    funFact: "少量で強力なゲルを形成できるため、様々な製品に使われます。",
  },
  {
    id: "xanthan-gum",
    nameJa: "キサンタンガム",
    nameInci: "Xanthan Gum",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "微生物が産生する天然の多糖類で、増粘・安定化剤として使われます。",
    funFact: "食品にも使われる安全性の高い増粘剤です。",
  },
  {
    id: "hydroxyethylcellulose",
    nameJa: "ヒドロキシエチルセルロース",
    nameInci: "Hydroxyethylcellulose",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "セルロース由来の増粘剤で、透明なジェルを作るのに適しています。",
    funFact: "植物由来のセルロースを化学修飾した天然系増粘剤です。",
  },
  {
    id: "hexanediol",
    nameJa: "1,2-ヘキサンジオール",
    nameInci: "1,2-Hexanediol",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "保湿と防腐補助の両方に使われるマルチ機能成分です。",
    funFact: "パラベンフリー処方で代替的に使用されることの多い成分です。",
  },
  {
    id: "caprylyl-glycol",
    nameJa: "カプリリルグリコール",
    nameInci: "Caprylyl Glycol",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "保湿と防腐補助の両機能を持つ成分で、1,2-ヘキサンジオールと組み合わせて使われます。",
  },
  {
    id: "ethylhexylglycerin",
    nameJa: "エチルヘキシルグリセリン",
    nameInci: "Ethylhexylglycerin",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "グリセリン誘導体の防腐補助・保湿成分です。",
    funFact: "天然由来の植物性グリセリンを原料とした成分です。",
  },
  {
    id: "disodium-edta",
    nameJa: "EDTA-2Na",
    nameInci: "Disodium EDTA",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "キレート剤として製品の安定性を高めるために配合されます。",
    funFact: "金属イオンを捕捉することで、製品の変色や防腐効果の低下を防ぎます。",
  },
  {
    id: "sodium-hydroxide",
    nameJa: "水酸化Na",
    nameInci: "Sodium Hydroxide",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "pH調整剤として微量に配合され、製品の酸性度を適切に保ちます。",
    funFact: "苛性ソーダとも呼ばれますが、化粧品ではpH調整のごく微量のみ使用されます。",
  },
  {
    id: "sodium-citrate",
    nameJa: "クエン酸Na",
    nameInci: "Sodium Citrate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "pH調整・緩衝剤として使用される成分です。",
    funFact: "食品添加物としても広く使われる安全性の高い成分です。",
  },
  {
    id: "polysorbate-20",
    nameJa: "ポリソルベート20",
    nameInci: "Polysorbate 20",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "水溶性の乳化剤・可溶化剤として幅広く使用されます。",
    funFact: "食品にも使用される安全性の高い非イオン性界面活性剤です。",
  },
  {
    id: "cocamidopropyl-betaine",
    nameJa: "コカミドプロピルベタイン",
    nameInci: "Cocamidopropyl Betaine",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "ヤシ油由来の両性界面活性剤で、比較的マイルドな洗浄成分として使われます。",
    funFact: "泡立ちや洗い上がりの感触を調整する目的でも使われます。",
  },

  // ─── UV成分 ──────────────────────────────────────────────
  {
    id: "ethylhexyl-methoxycinnamate",
    nameJa: "メトキシケイヒ酸エチルヘキシル",
    nameInci: "Ethylhexyl Methoxycinnamate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "UVB（紫外線B波）を吸収する有機系紫外線吸収剤です。",
    funFact: "最も広く使用されている紫外線吸収剤の一つです。",
  },
  {
    id: "zinc-oxide",
    nameJa: "酸化亜鉛",
    nameInci: "Zinc Oxide",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "UVA・UVBを物理的に反射・散乱させる無機系紫外線散乱剤です。",
    funFact: "ノンケミカル（物理的紫外線防止剤）として使われることがあります。",
  },
  {
    id: "titanium-dioxide",
    nameJa: "酸化チタン",
    nameInci: "Titanium Dioxide",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "UVB・一部UVAを物理的に反射させる無機系紫外線散乱剤です。",
    funFact: "白色顔料としても幅広く使用されています。",
  },
  {
    id: "avobenzone",
    nameJa: "t-ブチルメトキシジベンゾイルメタン",
    nameInci: "Butyl Methoxydibenzoylmethane",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "アボベンゾンとも呼ばれ、UVAを広範囲に吸収する紫外線吸収剤です。",
    funFact: "光に不安定な特性があるため、安定化剤と組み合わせて使われます。",
  },
  {
    id: "tinosorb-s",
    nameJa: "ビスエチルヘキシルオキシフェノールメトキシフェニルトリアジン",
    nameInci: "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine",
    categories: [],
    rarity: "rare",
    genre: "base",
    color: "#7C6AE8",
    note: "Tinosorb Sの名で知られる、UVAとUVBを幅広くカバーする次世代紫外線吸収剤です。",
    funFact: "欧州では承認されていますが、米国FDAではまだ審査中の成分です。",
  },

  // ─── バイオテク・発酵成分 ─────────────────────────────────
  {
    id: "galactomyces-ferment",
    nameJa: "ガラクトミセス培養液",
    nameInci: "Galactomyces Ferment Filtrate",
    categories: ["brightening", "moisturizing"],
    rarity: "rare",
    genre: "ferment",
    color: "#7C6AE8",
    note: "清酒酵母の一種を発酵させた培養液で、整肌・保湿目的で配合されます。",
    funFact: "酒造りの杜氏さんの手が白くきれいなことから研究が始まった成分です。",
  },
  {
    id: "bifida-ferment-lysate",
    nameJa: "ビフィズス菌溶解質",
    nameInci: "Bifida Ferment Lysate",
    categories: ["barrier", "brightening"],
    rarity: "rare",
    genre: "ferment",
    color: "#7C6AE8",
    note: "ビフィズス菌を発酵・溶解して得られるバイオテクノロジー由来の成分です。",
    funFact: "腸に良いとされるビフィズス菌の成分が肌のバリア機能にも役立ちます。",
  },
  {
    id: "lactobacillus-ferment",
    nameJa: "乳酸桿菌発酵液",
    nameInci: "Lactobacillus Ferment",
    categories: ["soothing", "moisturizing"],
    rarity: "uncommon",
    genre: "ferment",
    color: "#80CBC4",
    note: "乳酸菌を発酵させた液で、肌の常在菌バランスをサポートする成分です。",
    funFact: "プロバイオティクスコスメのブームとともに注目度が高まっています。",
  },

  // ─── 植物エキス ───────────────────────────────────────────
  {
    id: "rosa-damascena-water",
    nameJa: "ダマスクバラ花水",
    nameInci: "Rosa Damascena Flower Water",
    categories: ["soothing", "moisturizing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "ダマスクローズの蒸留水で、香り豊かな保湿・鎮静成分です。",
    funFact: "ローズウォーターは数千年前のペルシャで初めて製造されたとされています。",
  },
  {
    id: "pomegranate-extract",
    nameJa: "ザクロ果実エキス",
    nameInci: "Punica Granatum Fruit Extract",
    categories: ["brightening", "soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "ザクロから得られるポリフェノール豊富なエキスです。",
    funFact: "古代ギリシャ・ローマ時代から薬用植物として使われてきた歴史があります。",
  },
  {
    id: "licorice-extract",
    nameJa: "カンゾウ根エキス",
    nameInci: "Glycyrrhiza Glabra Root Extract",
    categories: ["brightening", "soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "甘草の根から得られるエキスで、整肌・鎮静の両作用を持ちます。",
    funFact: "漢方でも広く使われる甘草は、スキンケアでも有効性が研究されています。",
  },
  {
    id: "noni-extract",
    nameJa: "ヤエヤマアオキ果実エキス",
    nameInci: "Morinda Citrifolia Fruit Extract",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "ノニとも呼ばれる南国植物の果実から得られるエキスです。",
    funFact: "ポリネシアの伝統医学で「奇跡の植物」として使われてきました。",
  },

  // ─── 追加: 整肌系 ─────────────────────────────────────────
  {
    id: "4msk",
    nameJa: "4MSK",
    nameInci: "4-Methoxysalicylic Acid Potassium Salt",
    categories: ["brightening"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "資生堂が開発した医薬部外品有効成分で、整肌系に分類されます。",
    funFact: "サリチル酸誘導体として開発された日本発の成分です。",
  },
  {
    id: "ellagic-acid",
    nameJa: "エラグ酸",
    nameInci: "Ellagic Acid",
    categories: ["brightening"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "ザクロやイチゴなどに含まれるポリフェノールの一種で、整肌系成分です。",
    funFact: "ライオンが医薬部外品有効成分として承認を取得した成分です。",
  },
  {
    id: "magnesium-ascorbyl-phosphate",
    nameJa: "リン酸アスコルビルMg",
    nameInci: "Magnesium Ascorbyl Phosphate",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#CE93D8",
    note: "水溶性の安定型ビタミンC誘導体で、整肌成分として配合されます。",
    funFact: "医薬部外品有効成分としても認められている安定型ビタミンC誘導体です。",
  },
  {
    id: "ascorbyl-tetraisopalmitate",
    nameJa: "テトラヘキシルデカン酸アスコルビル",
    nameInci: "Ascorbyl Tetraisopalmitate",
    categories: ["brightening"],
    rarity: "rare",
    genre: "vitamin",
    color: "#CE93D8",
    note: "油溶性のビタミンC誘導体で、皮脂となじみやすく浸透性に優れます。",
    funFact: "VCIP（ビタミンCイソパルミテート）とも呼ばれます。",
  },
  {
    id: "glutathione",
    nameJa: "グルタチオン",
    nameInci: "Glutathione",
    categories: ["brightening"],
    rarity: "legendary",
    genre: "amino_acid",
    color: "#F59E0B",
    note: "3つのアミノ酸からなるトリペプチドで、体内の抗酸化防御を担う希少成分です。",
    funFact: "肝臓の解毒にも関わる「マスター抗酸化物質」と呼ばれています。",
  },
  {
    id: "azelaic-acid",
    nameJa: "アゼライン酸",
    nameInci: "Azelaic Acid",
    categories: ["brightening", "keratin"],
    rarity: "uncommon",
    genre: "acid",
    color: "#CE93D8",
    note: "穀物由来のジカルボン酸で、整肌・角質ケアの両面に作用します。",
    funFact: "ヨーロッパではニキビ治療薬としても処方される成分です。",
  },
  {
    id: "ferulic-acid",
    nameJa: "フェルラ酸",
    nameInci: "Ferulic Acid",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#CE93D8",
    note: "米ぬかなどに含まれるポリフェノールで、整肌成分として配合されます。",
    funFact: "ビタミンCやEと組み合わせると相乗効果があると報告されています。",
  },
  {
    id: "mulberry-extract",
    nameJa: "クワエキス",
    nameInci: "Morus Alba Root Extract",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "桑の根皮から得られる整肌系エキスです。",
    funFact: "漢方では「桑白皮（ソウハクヒ）」として知られています。",
  },
  {
    id: "cysteamine",
    nameJa: "システアミン",
    nameInci: "Cysteamine",
    categories: ["brightening"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "体内にも存在するアミノチオール化合物で、整肌系成分として注目されています。",
    funFact: "もともとシスチン蓄積症の治療薬として開発されました。",
  },
  {
    id: "alpha-lipoic-acid",
    nameJa: "α-リポ酸",
    nameInci: "Thioctic Acid",
    categories: ["brightening"],
    rarity: "rare",
    genre: "vitamin",
    color: "#CE93D8",
    note: "水溶性・油溶性両方の性質を持つ抗酸化成分です。",
    funFact: "赤色のカロテノイドとして知られ、ビタミンCやEとの関係でも語られることがあります。",
  },
  {
    id: "rucinol",
    nameJa: "ルシノール",
    nameInci: "4-n-Butylresorcinol",
    categories: ["brightening"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "ポーラが開発した医薬部外品有効成分で、整肌系成分です。",
    funFact: "レゾルシノール誘導体として合成されたオリジナル成分です。",
  },
  {
    id: "linoleic-acid",
    nameJa: "リノール酸",
    nameInci: "Linoleic Acid",
    categories: ["brightening", "barrier"],
    rarity: "common",
    genre: "botanical",
    color: "#CE93D8",
    note: "必須脂肪酸の一つで、肌のバリア機能と整肌に関わります。",
    funFact: "セラミドの原料となる重要な脂肪酸です。",
  },
  {
    id: "placenta-extract",
    nameJa: "プラセンタエキス",
    nameInci: "Placenta Extract",
    categories: ["brightening", "turnover"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "哺乳動物の胎盤から得られるエキスで、整肌・ハリ系に分類されます。",
    funFact: "クレオパトラも愛用していたという伝説がある成分です。",
    caution: "動物由来成分のため、原料の安全管理が重要とされています。",
  },
  {
    id: "licorice-glabridin",
    nameJa: "グラブリジン",
    nameInci: "Glabridin",
    categories: ["brightening"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "甘草の根から得られるフラボノイドで、高い整肌作用を持ちます。",
    funFact: "油溶性甘草エキスの主要成分として知られています。",
  },
  {
    id: "chamomile-et",
    nameJa: "カモミラET",
    nameInci: "Chamomilla Recutita Extract",
    categories: ["brightening", "soothing"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "花王が開発したカモミール由来の医薬部外品有効成分です。",
    funFact: "カモミールのエンドセリン抑制効果に着目して開発されました。",
  },
  {
    id: "ascorbic-acid-2-glucoside",
    nameJa: "アスコルビン酸2-グルコシド",
    nameInci: "Ascorbic Acid 2-Glucoside",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#CE93D8",
    note: "安定型ビタミンC誘導体で、医薬部外品有効成分にも指定されています。",
    funFact: "林原が開発した日本発の安定型ビタミンC誘導体です。",
  },
  {
    id: "aminocaproic-acid",
    nameJa: "アミノカプロン酸",
    nameInci: "Aminocaproic Acid",
    categories: ["brightening", "soothing"],
    rarity: "common",
    genre: "botanical",
    color: "#CE93D8",
    note: "抗プラスミン作用を持つアミノ酸誘導体で、肌荒れ防止に使われます。",
    funFact: "医薬品としても使用される歴史のある成分です。",
  },
  {
    id: "nicotinamide-mononucleotide",
    nameJa: "ニコチンアミドモノヌクレオチド",
    nameInci: "Nicotinamide Mononucleotide",
    categories: ["brightening", "turnover"],
    rarity: "legendary",
    genre: "vitamin",
    color: "#F59E0B",
    note: "NMNとも呼ばれる次世代の整肌・エイジングケア成分です。",
    funFact: "NAD+の前駆体として細胞のエネルギー代謝に関わることで注目されています。",
  },
  {
    id: "gallic-acid",
    nameJa: "没食子酸",
    nameInci: "Gallic Acid",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "緑茶やワインに含まれるポリフェノールの一種で、整肌成分として使われます。",
    funFact: "タンニンの基本構造単位として広く植物界に存在します。",
  },
  {
    id: "deoxyarbutin",
    nameJa: "デオキシアルブチン",
    nameInci: "Deoxyarbutin",
    categories: ["brightening"],
    rarity: "rare",
    genre: "botanical",
    color: "#CE93D8",
    note: "アルブチンの改良型で、より高い整肌効果が期待される成分です。",
    funFact: "通常のアルブチンより350倍高い活性があるとの報告があります。",
  },

  // ─── 追加: ハリ・弾力系 ───────────────────────────────────
  {
    id: "palmitoyl-pentapeptide-4",
    nameJa: "パルミトイルペンタペプチド-4",
    nameInci: "Palmitoyl Pentapeptide-4",
    categories: ["turnover"],
    rarity: "legendary",
    genre: "peptide",
    color: "#F59E0B",
    note: "マトリキシルとして知られる5つのアミノ酸からなるペプチド成分です。",
    funFact: "コラーゲンの合成を促すシグナルペプチドとして開発されました。",
  },
  {
    id: "tripeptide-1",
    nameJa: "トリペプチド-1",
    nameInci: "Tripeptide-1",
    categories: ["turnover"],
    rarity: "rare",
    genre: "peptide",
    color: "#FFB74D",
    note: "3つのアミノ酸からなるペプチドで、コラーゲン合成を促すシグナルペプチドです。",
    funFact: "GHK（グリシン-ヒスチジン-リジン）配列を持つペプチドです。",
  },
  {
    id: "sh-oligopeptide-1",
    nameJa: "ヒトオリゴペプチド-1（EGF）",
    nameInci: "sh-Oligopeptide-1",
    categories: ["turnover"],
    rarity: "legendary",
    genre: "peptide",
    color: "#F59E0B",
    note: "上皮成長因子（EGF）として知られる成長因子型ペプチドです。",
    funFact: "発見者のスタンリー・コーエン博士は1986年にノーベル生理学・医学賞を受賞しました。",
  },
  {
    id: "sh-polypeptide-1",
    nameJa: "ヒトポリペプチド-1（FGF）",
    nameInci: "sh-Polypeptide-1",
    categories: ["turnover"],
    rarity: "legendary",
    genre: "peptide",
    color: "#F59E0B",
    note: "線維芽細胞増殖因子（FGF）として知られる成長因子型ペプチドです。",
    funFact: "繊維芽細胞に働きかけ、コラーゲンやエラスチンの産生を促します。",
  },
  {
    id: "acetyl-octapeptide-3",
    nameJa: "アセチルオクタペプチド-3",
    nameInci: "Acetyl Octapeptide-3",
    categories: ["turnover"],
    rarity: "rare",
    genre: "peptide",
    color: "#FFB74D",
    note: "SNAP-25ペプチドとも呼ばれ、8つのアミノ酸からなるペプチドです。",
    funFact: "アルジレリンの改良型として開発された次世代ペプチドです。",
  },
  {
    id: "palmitoyl-tripeptide-5",
    nameJa: "パルミトイルトリペプチド-5",
    nameInci: "Palmitoyl Tripeptide-5",
    categories: ["turnover"],
    rarity: "rare",
    genre: "peptide",
    color: "#FFB74D",
    note: "TGF-βを模倣するペプチドで、コラーゲン合成を促進します。",
    funFact: "SYN-COLL（シンコル）の商品名で知られるペプチドです。",
  },
  {
    id: "elastin",
    nameJa: "エラスチン",
    nameInci: "Elastin",
    categories: ["turnover", "moisturizing"],
    rarity: "uncommon",
    genre: "peptide",
    color: "#FFB74D",
    note: "肌の弾力を維持する繊維状タンパク質で、保湿・ハリ系に分類されます。",
    funFact: "真皮中のエラスチンは約2〜4%ですが、肌の弾力に大きく関わっています。",
  },
  {
    id: "proteoglycan",
    nameJa: "プロテオグリカン",
    nameInci: "Hydrolyzed Proteoglycan",
    categories: ["turnover", "moisturizing"],
    rarity: "rare",
    genre: "peptide",
    color: "#FFB74D",
    note: "サケの鼻軟骨から抽出される糖タンパク質で、保湿とハリに優れた成分です。",
    funFact: "弘前大学の研究により、サケの鼻軟骨から効率的な抽出法が開発されました。",
  },
  {
    id: "stem-cell-extract",
    nameJa: "リンゴ果実培養細胞エキス",
    nameInci: "Malus Domestica Fruit Cell Culture Extract",
    categories: ["turnover"],
    rarity: "rare",
    genre: "botanical",
    color: "#FFB74D",
    note: "希少なスイスリンゴの幹細胞を培養して得られるエキスです。",
    funFact: "4ヶ月経っても腐らないスイスの希少リンゴ「ウトビラー・スパトラウバー」由来です。",
  },
  {
    id: "idebenone",
    nameJa: "イデベノン",
    nameInci: "Idebenone",
    categories: ["turnover", "brightening"],
    rarity: "rare",
    genre: "vitamin",
    color: "#FFB74D",
    note: "CoQ10の合成アナログで、高い抗酸化力を持つハリ系成分です。",
    funFact: "EPF（環境保護因子）テストでビタミンCやEを上回る抗酸化力が報告されています。",
  },
  {
    id: "carnosine",
    nameJa: "カルノシン",
    nameInci: "Carnosine",
    categories: ["turnover"],
    rarity: "uncommon",
    genre: "amino_acid",
    color: "#FFB74D",
    note: "2つのアミノ酸からなるジペプチドで、整肌成分として配合されます。",
    funFact: "筋肉や脳に豊富に存在する天然のジペプチドです。",
  },
  {
    id: "dmae",
    nameJa: "DMAE",
    nameInci: "Dimethyl MEA",
    categories: ["turnover"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#FFB74D",
    note: "ジメチルアミノエタノールの略で、引き締め効果が期待されるハリ系成分です。",
    funFact: "魚類に多く含まれる成分で、即時的な引き締め効果で注目されています。",
  },
  {
    id: "dipeptide-2",
    nameJa: "ジペプチド-2",
    nameInci: "Dipeptide-2",
    categories: ["turnover"],
    rarity: "uncommon",
    genre: "peptide",
    color: "#FFB74D",
    note: "目元のケアに使われるペプチドで、リンパの流れをサポートします。",
    funFact: "アイセリルの商品名で知られ、目元用製品に多く配合されます。",
  },
  {
    id: "myristoyl-pentapeptide-17",
    nameJa: "ミリストイルペンタペプチド-17",
    nameInci: "Myristoyl Pentapeptide-17",
    categories: ["turnover"],
    rarity: "rare",
    genre: "peptide",
    color: "#FFB74D",
    note: "まつげや眉毛の育毛に関わるペプチドとして注目されています。",
    funFact: "ケラチンの産生を促すシグナルペプチドです。",
  },
  {
    id: "palmitoyl-tetrapeptide-7",
    nameJa: "パルミトイルテトラペプチド-7",
    nameInci: "Palmitoyl Tetrapeptide-7",
    categories: ["turnover", "soothing"],
    rarity: "rare",
    genre: "peptide",
    color: "#FFB74D",
    note: "炎症を抑えハリを与えるデュアル機能ペプチドです。",
    funFact: "マトリキシル3000の構成成分の一つです。",
  },
  {
    id: "retinyl-retinoate",
    nameJa: "レチニルレチノエート",
    nameInci: "Retinyl Retinoate",
    categories: ["turnover"],
    rarity: "rare",
    genre: "vitamin",
    color: "#FFB74D",
    note: "レチノールとレチノイン酸のハイブリッド型で、刺激が少ないビタミンA誘導体です。",
    funFact: "韓国の研究機関で開発された新しいタイプのレチノイドです。",
  },
  {
    id: "retinyl-linoleate",
    nameJa: "リノール酸レチノール",
    nameInci: "Retinyl Linoleate",
    categories: ["turnover"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#FFB74D",
    note: "レチノールとリノール酸のエステルで、穏やかなビタミンA誘導体です。",
    funFact: "必須脂肪酸との結合により安定性と穏やかさを両立しています。",
  },
  {
    id: "nana-peptide-1",
    nameJa: "ノナペプチド-1",
    nameInci: "Nonapeptide-1",
    categories: ["turnover", "brightening"],
    rarity: "rare",
    genre: "peptide",
    color: "#FFB74D",
    note: "9つのアミノ酸からなるペプチドで、整肌・ハリ系に分類されます。",
    funFact: "メラノトロピンを模倣したペプチドとして設計されました。",
  },

  // ─── 追加: 保湿系 ─────────────────────────────────────────
  {
    id: "saccharide-isomerate",
    nameJa: "サッカライドイソメレート",
    nameInci: "Saccharide Isomerate",
    categories: ["moisturizing"],
    rarity: "uncommon",
    genre: "water",
    color: "#4FC3F7",
    note: "肌の天然保湿因子に似た構造を持つ糖類由来の保湿成分です。",
    funFact: "ペンタバイティンの商品名で知られ、角質に結合して長時間保湿します。",
  },
  {
    id: "polyglutamic-acid",
    nameJa: "ポリグルタミン酸",
    nameInci: "Polyglutamic Acid",
    categories: ["moisturizing"],
    rarity: "uncommon",
    genre: "water",
    color: "#4FC3F7",
    note: "納豆のネバネバ成分として知られ、ヒアルロン酸以上の保湿力を持つとされます。",
    funFact: "ヒアルロン酸の約10倍の保水力があるとの報告もあります。",
  },
  {
    id: "acetyl-glucosamine",
    nameJa: "アセチルグルコサミン",
    nameInci: "Acetyl Glucosamine",
    categories: ["moisturizing", "brightening"],
    rarity: "uncommon",
    genre: "water",
    color: "#4FC3F7",
    note: "ヒアルロン酸の前駆体となるアミノ糖で、保湿と整肌に関わります。",
    funFact: "体内でヒアルロン酸の原料となるN-アセチルグルコサミンです。",
  },
  {
    id: "honey-extract",
    nameJa: "ハチミツエキス",
    nameInci: "Mel Extract",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#4FC3F7",
    note: "ハチミツ由来の保湿成分で、アミノ酸やミネラルが豊富に含まれます。",
    funFact: "古代エジプトのミイラの保存にもハチミツが使われていました。",
  },
  {
    id: "royal-jelly-extract",
    nameJa: "ローヤルゼリーエキス",
    nameInci: "Royal Jelly Extract",
    categories: ["moisturizing", "barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#4FC3F7",
    note: "女王蜂のための特別な分泌物から得られる栄養豊富な保湿成分です。",
    funFact: "働き蜂が分泌する乳白色の物質で、女王蜂だけの特別食です。",
  },
  {
    id: "hyaluronic-acid-crosspolymer",
    nameJa: "ヒアルロン酸クロスポリマーNa",
    nameInci: "Sodium Hyaluronate Crosspolymer",
    categories: ["moisturizing"],
    rarity: "rare",
    genre: "water",
    color: "#4FC3F7",
    note: "架橋型ヒアルロン酸で、通常のヒアルロン酸より長時間保湿が持続します。",
    funFact: "3D構造により肌表面にとどまりやすく、持続的な保湿効果があります。",
  },
  {
    id: "urea",
    nameJa: "尿素",
    nameInci: "Urea",
    categories: ["moisturizing", "keratin"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "天然保湿因子（NMF）の構成成分の一つで、角質を柔らかくする作用もあります。",
    funFact: "肌のNMFの約7%を占める重要な保湿成分です。",
    caution: "高濃度では刺激を感じる場合があります。傷のある部位への使用は避けてください。",
  },
  {
    id: "pca-na",
    nameJa: "PCA-Na",
    nameInci: "Sodium PCA",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "天然保湿因子（NMF）の主要成分で、高い吸湿性を持つ保湿成分です。",
    funFact: "NMFの約12%を占めるピロリドンカルボン酸のナトリウム塩です。",
  },
  {
    id: "propanediol",
    nameJa: "プロパンジオール",
    nameInci: "Propanediol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "トウモロコシ由来の保湿成分で、BGの代替として使われることもあります。",
    funFact: "100%植物由来で作れるため、ナチュラルコスメに多く採用されています。",
  },
  {
    id: "sodium-alginate",
    nameJa: "アルギン酸Na",
    nameInci: "Sodium Alginate",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "海藻由来の多糖類で、保湿・増粘効果があります。",
    funFact: "昆布やワカメなどの褐藻類から得られる天然成分です。",
  },
  {
    id: "mannitol",
    nameJa: "マンニトール",
    nameInci: "Mannitol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "海藻やキノコに含まれる糖アルコールの一種で、保湿作用があります。",
    funFact: "マナの木から発見されたことが名前の由来です。",
  },
  {
    id: "hydroxyproline",
    nameJa: "ヒドロキシプロリン",
    nameInci: "Hydroxyproline",
    categories: ["moisturizing", "turnover"],
    rarity: "uncommon",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "コラーゲンに特有のアミノ酸で、保湿とハリ系の両面に関わります。",
    funFact: "コラーゲン中のプロリンが酵素により変換されて生成されるアミノ酸です。",
  },
  {
    id: "alanine",
    nameJa: "アラニン",
    nameInci: "Alanine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "天然保湿因子（NMF）を構成するアミノ酸の一つです。",
    funFact: "絹糸のタンパク質フィブロインに多く含まれるアミノ酸です。",
  },
  {
    id: "lysine",
    nameJa: "リジン",
    nameInci: "Lysine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "必須アミノ酸の一つで、コラーゲン合成に必要な保湿成分です。",
    funFact: "体内で合成できない必須アミノ酸で、食品からの摂取が必要です。",
  },
  {
    id: "threonine",
    nameJa: "トレオニン",
    nameInci: "Threonine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "NMFを構成する必須アミノ酸の一つです。",
    funFact: "最後に発見された必須アミノ酸（1936年発見）です。",
  },
  {
    id: "valine",
    nameJa: "バリン",
    nameInci: "Valine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "分岐鎖アミノ酸（BCAA）の一つで、NMF構成成分です。",
  },
  {
    id: "isoleucine",
    nameJa: "イソロイシン",
    nameInci: "Isoleucine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "分岐鎖アミノ酸の一つで、肌のコンディショニングに関わります。",
  },
  {
    id: "leucine",
    nameJa: "ロイシン",
    nameInci: "Leucine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "BCAAの一つで、保湿・コンディショニング成分として配合されます。",
  },
  {
    id: "histidine",
    nameJa: "ヒスチジン",
    nameInci: "Histidine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "NMFの構成成分の一つで、肌のうるおいを保つアミノ酸です。",
    funFact: "紫外線からの保護作用もあるとされるアミノ酸です。",
  },
  {
    id: "phenylalanine",
    nameJa: "フェニルアラニン",
    nameInci: "Phenylalanine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "必須アミノ酸の一つで、NMF構成成分です。",
  },
  {
    id: "aspartic-acid",
    nameJa: "アスパラギン酸",
    nameInci: "Aspartic Acid",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "保湿作用を持つアミノ酸で、ミネラルの吸収を助けます。",
    funFact: "アスパラガスから発見されたことが名前の由来です。",
  },
  {
    id: "glutamic-acid",
    nameJa: "グルタミン酸",
    nameInci: "Glutamic Acid",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "NMFを構成するアミノ酸で、うま味成分としても知られます。",
    funFact: "味の素の主成分であるグルタミン酸ナトリウムの元になるアミノ酸です。",
  },
  {
    id: "cysteine",
    nameJa: "システイン",
    nameInci: "Cysteine",
    categories: ["moisturizing", "brightening"],
    rarity: "uncommon",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "含硫アミノ酸で、ケラチンの構成成分としても重要です。",
    funFact: "L-システインとして医薬品にも使われる成分です。",
  },
  {
    id: "tryptophan",
    nameJa: "トリプトファン",
    nameInci: "Tryptophan",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "必須アミノ酸の一つで、保湿成分として配合されます。",
    funFact: "セロトニンやメラトニンの前駆体となるアミノ酸です。",
  },
  {
    id: "methionine",
    nameJa: "メチオニン",
    nameInci: "Methionine",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "amino_acid",
    color: "#4FC3F7",
    note: "含硫必須アミノ酸で、保湿・コンディショニング成分です。",
  },
  {
    id: "ectoin",
    nameJa: "エクトイン",
    nameInci: "Ectoin",
    categories: ["moisturizing", "soothing"],
    rarity: "rare",
    genre: "water",
    color: "#4FC3F7",
    note: "極限環境微生物が産生する環状アミノ酸で、高い保護・保湿作用があります。",
    funFact: "砂漠やアルカリ湖に生息する好塩菌が身を守るために産生する成分です。",
  },
  {
    id: "beta-glucan",
    nameJa: "β-グルカン",
    nameInci: "Beta-Glucan",
    categories: ["moisturizing", "soothing"],
    rarity: "uncommon",
    genre: "water",
    color: "#4FC3F7",
    note: "キノコや酵母に含まれる多糖類で、保湿成分として配合されることがあります。",
    funFact: "アガリクスやシイタケなどのキノコの機能性成分としても有名です。",
  },
  {
    id: "erythritol",
    nameJa: "エリスリトール",
    nameInci: "Erythritol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "メロンやブドウにも含まれる天然糖アルコールで、保湿効果があります。",
    funFact: "カロリーゼロの天然甘味料としても使われている成分です。",
  },
  {
    id: "xylitol",
    nameJa: "キシリトール",
    nameInci: "Xylitol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "白樺などから得られる糖アルコールで、保湿作用があります。",
    funFact: "虫歯予防のガムで有名ですが、スキンケアでも保湿成分として活用されます。",
  },
  {
    id: "maltitol",
    nameJa: "マルチトール",
    nameInci: "Maltitol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "麦芽糖を還元して得られる糖アルコールの保湿成分です。",
  },
  {
    id: "raffinose",
    nameJa: "ラフィノース",
    nameInci: "Raffinose",
    categories: ["moisturizing"],
    rarity: "uncommon",
    genre: "water",
    color: "#4FC3F7",
    note: "ビートやユーカリに含まれるオリゴ糖で、肌のバリア機能をサポートします。",
    funFact: "腸活でも注目されるオリゴ糖がスキンケアにも活用されています。",
  },
  {
    id: "sucrose",
    nameJa: "スクロース",
    nameInci: "Sucrose",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "砂糖の主成分で、保湿・質感改良剤として化粧品にも使われます。",
  },
  {
    id: "sodium-lactate",
    nameJa: "乳酸Na",
    nameInci: "Sodium Lactate",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "water",
    color: "#4FC3F7",
    note: "NMFの主要構成成分の一つで、高い吸湿性を持つ保湿成分です。",
    funFact: "NMFの約12%を占める重要な保湿成分です。",
  },
  {
    id: "ceramide-1",
    nameJa: "セラミド1",
    nameInci: "Ceramide 1",
    categories: ["moisturizing", "barrier"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種で、長鎖脂肪酸を持ちます。",
    funFact: "セラミドの中でも特に角層のバリア機能に重要な型です。",
  },

  // ─── 追加: バリア系 ───────────────────────────────────────
  {
    id: "ceramide-ns",
    nameJa: "セラミドNS",
    nameInci: "Ceramide NS",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "ヒト型セラミドの一種で、角質層のバリア機能に関わります。",
    funFact: "「N」はノーマル脂肪酸、「S」はスフィンゴシン骨格を意味します。",
  },
  {
    id: "ceramide-as",
    nameJa: "セラミドAS",
    nameInci: "Ceramide AS",
    categories: ["barrier"],
    rarity: "rare",
    genre: "oil_lipid",
    color: "#81C784",
    note: "α-ヒドロキシ脂肪酸を含むヒト型セラミドです。",
    funFact: "「A」はα-ヒドロキシ、「S」はスフィンゴシンを意味します。",
  },
  {
    id: "lecithin",
    nameJa: "レシチン",
    nameInci: "Lecithin",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "大豆や卵黄から得られるリン脂質で、乳化や質感調整に使われます。",
    funFact: "細胞膜の主成分であるリン脂質の混合物です。",
  },
  {
    id: "sphingomyelin",
    nameJa: "スフィンゴミエリン",
    nameInci: "Sphingomyelin",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "細胞膜の構成成分であるスフィンゴ脂質の一種です。",
    funFact: "牛乳や卵黄に含まれ、肌のセラミド合成を促進するとされています。",
  },
  {
    id: "stearic-acid",
    nameJa: "ステアリン酸",
    nameInci: "Stearic Acid",
    categories: ["barrier"],
    rarity: "common",
    genre: "acid",
    color: "#81C784",
    note: "動植物油に含まれる飽和脂肪酸で、肌のバリア機能を支えます。",
    funFact: "石鹸の主要原料としても使われる脂肪酸です。",
  },
  {
    id: "palmitic-acid",
    nameJa: "パルミチン酸",
    nameInci: "Palmitic Acid",
    categories: ["barrier"],
    rarity: "common",
    genre: "acid",
    color: "#81C784",
    note: "パーム油に多く含まれる飽和脂肪酸で、肌のバリア機能に関わります。",
    funFact: "パーム油から発見されたことが名前の由来です。",
  },
  {
    id: "oleic-acid",
    nameJa: "オレイン酸",
    nameInci: "Oleic Acid",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "acid",
    color: "#81C784",
    note: "オリーブオイルに多く含まれる一価不飽和脂肪酸で、エモリエント効果があります。",
    funFact: "人の皮脂にも約30%含まれる脂肪酸です。",
  },
  {
    id: "meadowfoam-oil",
    nameJa: "メドウフォーム油",
    nameInci: "Limnanthes Alba Seed Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "メドウフォームの種子から得られる植物油で、高い安定性を持ちます。",
    funFact: "98%が長鎖脂肪酸で構成される非常にユニークな植物油です。",
  },
  {
    id: "evening-primrose-oil",
    nameJa: "月見草油",
    nameInci: "Oenothera Biennis Oil",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "月見草の種子から得られる植物油で、γ-リノレン酸が豊富です。",
    funFact: "γ-リノレン酸を含む希少な植物油として注目されています。",
  },
  {
    id: "camellia-oil",
    nameJa: "ツバキ油",
    nameInci: "Camellia Japonica Seed Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "日本原産のツバキの種子から得られる伝統的な植物油です。",
    funFact: "日本では平安時代から髪と肌のケアに使われてきた歴史ある油です。",
  },
  {
    id: "hemp-seed-oil",
    nameJa: "ヘンプシードオイル",
    nameInci: "Cannabis Sativa Seed Oil",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "麻の種子から得られる植物油で、オメガ3・6のバランスが優れています。",
    funFact: "ω-6とω-3を含む植物油として知られています。",
  },
  {
    id: "baobab-oil",
    nameJa: "バオバブ種子油",
    nameInci: "Adansonia Digitata Seed Oil",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "アフリカの「生命の木」バオバブの種子から得られる植物油です。",
    funFact: "バオバブの木は樹齢数千年にもなり、幹に水を蓄える巨木です。",
  },
  {
    id: "lanolin",
    nameJa: "ラノリン",
    nameInci: "Lanolin",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "羊毛脂とも呼ばれ、羊の毛から得られる天然のエモリエント成分です。",
    funFact: "人の皮脂に非常に近い組成を持つ天然の油脂です。",
    caution: "ウールアレルギーの方は使用に注意が必要です。",
  },
  {
    id: "avocado-oil",
    nameJa: "アボカド油",
    nameInci: "Persea Gratissima Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "アボカドの果肉から得られる栄養豊富な植物油です。",
    funFact: "ビタミンA・D・E・Kが豊富で「食べる美容液」とも呼ばれる果実の油です。",
  },
  {
    id: "grape-seed-oil",
    nameJa: "ブドウ種子油",
    nameInci: "Vitis Vinifera Seed Oil",
    categories: ["barrier"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "ブドウの種子から得られる軽いテクスチャーの植物油です。",
    funFact: "ワイン製造の副産物として生産される環境にやさしい植物油です。",
  },
  {
    id: "sweet-almond-oil",
    nameJa: "アーモンド油",
    nameInci: "Prunus Amygdalus Dulcis Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "スイートアーモンドの核から得られるマイルドな植物油です。",
    funFact: "ベビーオイルの原料としても使われるほど刺激が少ない植物油です。",
  },
  {
    id: "coconut-oil",
    nameJa: "ヤシ油",
    nameInci: "Cocos Nucifera Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "ココナッツの果肉から得られる飽和脂肪酸が豊富な植物油です。",
    funFact: "ラウリン酸を多く含むことでも知られています。",
  },
  {
    id: "apricot-kernel-oil",
    nameJa: "アンズ核油",
    nameInci: "Prunus Armeniaca Kernel Oil",
    categories: ["barrier"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#81C784",
    note: "杏の核から得られる軽い植物油で、オレイン酸が豊富です。",
  },
  {
    id: "marula-oil",
    nameJa: "マルラオイル",
    nameInci: "Sclerocarya Birrea Seed Oil",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "南アフリカ産マルラの実から得られる抗酸化作用の高いオイルです。",
    funFact: "アルガンオイルの約3.6倍の抗酸化力があるとされています。",
  },
  {
    id: "tamanu-oil",
    nameJa: "タマヌオイル",
    nameInci: "Calophyllum Inophyllum Seed Oil",
    categories: ["barrier", "soothing"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "タマヌの実から得られる緑色のオイルで、エモリエント成分として使われます。",
    funFact: "ポリネシアでは「緑の金」と呼ばれ、伝統的な治療オイルです。",
  },
  {
    id: "rice-ceramide",
    nameJa: "コメヌカスフィンゴ糖脂質",
    nameInci: "Oryza Sativa Bran Sphingoglycolipid",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "米ぬかから得られる植物性セラミドで、バリア機能をサポートします。",
    funFact: "日本の米文化から生まれた、植物由来のセラミド原料です。",
  },
  {
    id: "hydrogenated-lecithin",
    nameJa: "水素添加レシチン",
    nameInci: "Hydrogenated Lecithin",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "レシチンを水素添加して安定性を高めたリン脂質です。",
    funFact: "リポソーム製剤の主要原料として使われることが多い成分です。",
  },
  {
    id: "behenic-acid",
    nameJa: "ベヘン酸",
    nameInci: "Behenic Acid",
    categories: ["barrier"],
    rarity: "common",
    genre: "acid",
    color: "#81C784",
    note: "菜種油に含まれる長鎖飽和脂肪酸で、エモリエント効果があります。",
  },
  {
    id: "myristic-acid",
    nameJa: "ミリスチン酸",
    nameInci: "Myristic Acid",
    categories: ["barrier"],
    rarity: "common",
    genre: "acid",
    color: "#81C784",
    note: "ヤシ油やパーム核油に多い飽和脂肪酸で、洗浄・乳化に使われます。",
    funFact: "ナツメグ（Myristica fragrans）から発見されたことが名前の由来です。",
  },
  {
    id: "lauric-acid",
    nameJa: "ラウリン酸",
    nameInci: "Lauric Acid",
    categories: ["barrier"],
    rarity: "common",
    genre: "acid",
    color: "#81C784",
    note: "ココナッツオイルに約50%含まれる中鎖脂肪酸です。",
    funFact: "月桂樹（Laurus）から名前が付いた脂肪酸です。",
  },

  // ─── 追加: 鎮静系 ─────────────────────────────────────────
  {
    id: "madecassoside",
    nameJa: "マデカッソシド",
    nameInci: "Madecassoside",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "base",
    color: "#80CBC4",
    note: "ツボクサに含まれるトリテルペン配糖体で、CICA系の整肌成分として知られています。",
    funFact: "CICAコスメの主要有効成分の一つです。",
  },
  {
    id: "asiaticoside",
    nameJa: "アシアチコシド",
    nameInci: "Asiaticoside",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "base",
    color: "#80CBC4",
    note: "ツボクサの主要成分の一つで、整肌成分として配合されます。",
    funFact: "トラが傷を負うとツボクサに体を擦り付けたという伝説があります。",
  },
  {
    id: "calendula-extract",
    nameJa: "カレンデュラエキス",
    nameInci: "Calendula Officinalis Flower Extract",
    categories: ["soothing"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "マリーゴールドの花から得られるエキスで、整肌目的で配合されることがあります。",
    funFact: "中世ヨーロッパでは「太陽のハーブ」として重宝されていました。",
  },
  {
    id: "mugwort-extract",
    nameJa: "ヨモギエキス",
    nameInci: "Artemisia Vulgaris Extract",
    categories: ["soothing"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "ヨモギから得られるエキスで、日本・韓国で人気の鎮静成分です。",
    funFact: "お灸の「もぐさ」はヨモギの葉裏の綿毛から作られます。",
  },
  {
    id: "tea-tree-oil",
    nameJa: "ティーツリー油",
    nameInci: "Melaleuca Alternifolia Leaf Oil",
    categories: ["soothing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#80CBC4",
    note: "オーストラリア原産のティーツリーから得られる精油で、清浄感のある植物成分として使われます。",
    funFact: "オーストラリアの先住民アボリジニが古くから薬用に使っていた植物です。",
    caution: "精油のため、敏感肌の方はパッチテストを推奨します。",
  },
  {
    id: "hinokitiol",
    nameJa: "ヒノキチオール",
    nameInci: "Hinokitiol",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "base",
    color: "#80CBC4",
    note: "タイワンヒノキから発見されたトロポロン系化合物で、整肌目的で使われることがあります。",
    funFact: "日本の野副鉄男博士が1936年に発見した成分です。",
  },
  {
    id: "guaiazulene",
    nameJa: "グアイアズレン",
    nameInci: "Guaiazulene",
    categories: ["soothing"],
    rarity: "rare",
    genre: "base",
    color: "#80CBC4",
    note: "カモミールやグアヤク木から得られる青色の鎮静成分です。",
    funFact: "アズレンより安定性が高く、濃い青色を呈する成分です。",
  },
  {
    id: "lavender-oil",
    nameJa: "ラベンダー油",
    nameInci: "Lavandula Angustifolia Oil",
    categories: ["soothing"],
    rarity: "common",
    genre: "oil_lipid",
    color: "#80CBC4",
    note: "ラベンダーの花から得られる精油で、香りづけやスキンケア製品に使われます。",
    funFact: "ラテン語の「lavare（洗う）」が名前の由来です。",
  },
  {
    id: "rosemary-extract",
    nameJa: "ローズマリーエキス",
    nameInci: "Rosmarinus Officinalis Leaf Extract",
    categories: ["soothing", "brightening"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "ローズマリーの葉から得られるエキスで、整肌成分として配合されます。",
    funFact: "「海のしずく」を意味するラテン語が名前の由来です。",
  },
  {
    id: "licorice-leaf-extract",
    nameJa: "甘草葉エキス",
    nameInci: "Glycyrrhiza Uralensis Leaf Extract",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "甘草の葉から得られるエキスで、整肌成分として配合されます。",
    funFact: "根のエキスとは異なる成分組成を持ち、ポリフェノールが豊富です。",
  },
  {
    id: "willow-bark-extract",
    nameJa: "セイヨウシロヤナギ樹皮エキス",
    nameInci: "Salix Alba Bark Extract",
    categories: ["soothing", "keratin"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "ヤナギの樹皮から得られるエキスで、角質ケア系の製品に使われます。",
    funFact: "アスピリン（サリチル酸）はヤナギの樹皮から発見されました。",
  },
  {
    id: "eucalyptus-extract",
    nameJa: "ユーカリエキス",
    nameInci: "Eucalyptus Globulus Leaf Extract",
    categories: ["soothing"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "ユーカリの葉から得られるエキスで、清浄感のある植物エキスとして使われます。",
    funFact: "コアラの主食として知られるユーカリは、約700種が存在します。",
  },
  {
    id: "turmeric-extract",
    nameJa: "ウコンエキス",
    nameInci: "Curcuma Longa Root Extract",
    categories: ["soothing", "brightening"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "ウコン（ターメリック）の根茎から得られる黄色のエキスです。",
    funFact: "インドのアーユルヴェーダで何千年も使われてきたスパイスです。",
  },
  {
    id: "ginger-extract",
    nameJa: "ショウガエキス",
    nameInci: "Zingiber Officinale Root Extract",
    categories: ["soothing"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "ショウガの根茎から得られるエキスで、整肌目的で配合されることがある成分です。",
    funFact: "「ジンジャー」はサンスクリット語の「角の形」に由来します。",
  },
  {
    id: "peony-extract",
    nameJa: "ボタンエキス",
    nameInci: "Paeonia Suffruticosa Root Extract",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "牡丹の根皮から得られるエキスで、整肌成分として配合されます。",
    funFact: "漢方では「牡丹皮（ボタンピ）」として使われる生薬です。",
  },
  {
    id: "witch-hazel-extract",
    nameJa: "ハマメリスエキス",
    nameInci: "Hamamelis Virginiana Leaf Extract",
    categories: ["soothing"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "ハマメリスの葉から得られる収れん・鎮静エキスです。",
    funFact: "北米先住民が古くから薬用に使っていた植物です。",
  },
  {
    id: "licorice-root-flavonoid",
    nameJa: "カンゾウフラボノイド",
    nameInci: "Glycyrrhiza Glabra Root Flavonoid Extract",
    categories: ["soothing", "brightening"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "甘草根から得られるフラボノイド成分で、整肌成分として配合されます。",
  },
  {
    id: "sakura-extract",
    nameJa: "サクラ葉エキス",
    nameInci: "Prunus Speciosa Leaf Extract",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "ソメイヨシノの葉から得られるエキスで、保湿・整肌目的で配合されます。",
    funFact: "桜餅の葉に含まれるクマリンでも知られています。",
  },
  {
    id: "propolis-extract",
    nameJa: "プロポリスエキス",
    nameInci: "Propolis Extract",
    categories: ["soothing", "barrier"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#80CBC4",
    note: "ミツバチが樹脂から作る天然物質で、整肌目的で配合されることがあります。",
    funFact: "「プロポリス」はギリシャ語で「都市の前の防壁」を意味します。",
  },
  {
    id: "madecassic-acid",
    nameJa: "マデカシン酸",
    nameInci: "Madecassic Acid",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "acid",
    color: "#80CBC4",
    note: "ツボクサに含まれるトリテルペン酸で、整肌成分として使われます。",
    funFact: "マデカッソシドとともにCICA成分の主要活性物質です。",
  },
  {
    id: "asiatic-acid",
    nameJa: "アシアチン酸",
    nameInci: "Asiatic Acid",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "acid",
    color: "#80CBC4",
    note: "ツボクサに含まれるトリテルペン酸の一種です。",
    funFact: "アシアチコシドの非糖部分（アグリコン）がアシアチン酸です。",
  },
  {
    id: "cornflower-extract",
    nameJa: "ヤグルマギクエキス",
    nameInci: "Centaurea Cyanus Flower Extract",
    categories: ["soothing"],
    rarity: "common",
    genre: "botanical",
    color: "#80CBC4",
    note: "矢車菊の花から得られる青いエキスで、整肌目的で配合されることがあります。",
    funFact: "フランスでは目の疲れを癒すハーブとして伝統的に使われてきました。",
  },

  // ─── 追加: 角質ケア系 ─────────────────────────────────────
  {
    id: "tartaric-acid",
    nameJa: "酒石酸",
    nameInci: "Tartaric Acid",
    categories: ["keratin"],
    rarity: "common",
    genre: "acid",
    color: "#90A4AE",
    note: "ワインやブドウに含まれるAHAの一種で、穏やかな角質ケア作用があります。",
    funFact: "ワイン樽の内側に結晶として付着することから「酒石酸」の名が付きました。",
  },
  {
    id: "phytic-acid",
    nameJa: "フィチン酸",
    nameInci: "Phytic Acid",
    categories: ["keratin", "brightening"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "穀物や豆類に含まれる有機酸で、穏やかな角質ケア・整肌作用があります。",
    funFact: "キレート作用により肌表面のミネラルを除去する独特の作用があります。",
  },
  {
    id: "papain",
    nameJa: "パパイン",
    nameInci: "Papain",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "base",
    color: "#90A4AE",
    note: "パパイヤ由来のタンパク質分解酵素で、角質を穏やかに分解します。",
    funFact: "パパイヤの乳液から得られる天然の酵素です。",
    caution: "酵素アレルギーの方は使用に注意が必要です。",
  },
  {
    id: "bromelain",
    nameJa: "ブロメライン",
    nameInci: "Bromelain",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "base",
    color: "#90A4AE",
    note: "パイナップル由来のタンパク質分解酵素で、角質ケアに使われます。",
    funFact: "パイナップルを食べると舌がピリピリするのはこの酵素の作用です。",
    caution: "酵素アレルギーの方は注意が必要です。",
  },
  {
    id: "pyruvic-acid",
    nameJa: "ピルビン酸",
    nameInci: "Pyruvic Acid",
    categories: ["keratin"],
    rarity: "rare",
    genre: "acid",
    color: "#90A4AE",
    note: "α-ケト酸の一種で、角質ケア成分として使われます。",
    funFact: "解糖系の最終産物として体内の代謝にも関わる有機酸です。",
    caution: "刺激が強いため、低濃度からの使用を推奨します。",
  },
  {
    id: "citric-acid-aha",
    nameJa: "クエン酸（角質ケア用）",
    nameInci: "Citric Acid",
    categories: ["keratin"],
    rarity: "common",
    genre: "acid",
    color: "#90A4AE",
    note: "柑橘類に含まれるAHAで、pH調整と穏やかな角質ケア作用があります。",
    funFact: "レモンに約5〜6%含まれる天然の有機酸です。",
  },
  {
    id: "lipase",
    nameJa: "リパーゼ",
    nameInci: "Lipase",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "base",
    color: "#90A4AE",
    note: "脂質分解酵素で、毛穴の皮脂を分解する角質ケア成分です。",
    funFact: "膵臓が分泌する消化酵素の一つですが、スキンケアにも応用されています。",
  },
  {
    id: "protease",
    nameJa: "プロテアーゼ",
    nameInci: "Protease",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "base",
    color: "#90A4AE",
    note: "タンパク質分解酵素の総称で、角質のタンパク質を分解します。",
    funFact: "洗剤にも使われるほど強力なタンパク質分解能力を持ちます。",
  },
  {
    id: "polyhydroxy-acid",
    nameJa: "ガラクトース",
    nameInci: "Galactose",
    categories: ["keratin", "moisturizing"],
    rarity: "uncommon",
    genre: "acid",
    color: "#90A4AE",
    note: "PHA（ポリヒドロキシ酸）の一種で、保湿しながら穏やかに角質ケアします。",
    funFact: "乳糖を構成する糖の一つで、AHAより刺激が少ないとされます。",
  },
  {
    id: "malic-acid-aha",
    nameJa: "リンゴ酸（角質ケア用）",
    nameInci: "Malic Acid",
    categories: ["keratin"],
    rarity: "common",
    genre: "acid",
    color: "#90A4AE",
    note: "リンゴなどに含まれるAHAで、穏やかな角質ケア作用があります。",
    funFact: "リンゴに多く含まれることから「リンゴ酸」と名付けられました。",
  },
  {
    id: "trichloroacetic-acid",
    nameJa: "トリクロロ酢酸",
    nameInci: "Trichloroacetic Acid",
    categories: ["keratin"],
    rarity: "rare",
    genre: "acid",
    color: "#90A4AE",
    note: "医療用ケミカルピーリングに使われる強力な角質除去成分です。",
    caution: "高濃度は医療専門家のみが使用する成分です。セルフケアでの使用は低濃度に限ります。",
  },
  {
    id: "subtilisin",
    nameJa: "サブチリシン",
    nameInci: "Subtilisin",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "base",
    color: "#90A4AE",
    note: "枯草菌由来のプロテアーゼで、角質を穏やかに分解する酵素です。",
    funFact: "微生物由来の酵素として洗剤や化粧品に幅広く使われています。",
  },

  // ─── 追加: 基剤・防腐・UV ─────────────────────────────────
  {
    id: "octocrylene",
    nameJa: "オクトクリレン",
    nameInci: "Octocrylene",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "UVB領域を吸収する紫外線吸収剤で、光安定性に優れます。",
    funFact: "他のUV吸収剤の光安定性を高める「光安定化剤」としても機能します。",
  },
  {
    id: "uvinul-a-plus",
    nameJa: "ユビナールAプラス",
    nameInci: "Diethylamino Hydroxybenzoyl Hexyl Benzoate",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "UVA領域を吸収する紫外線吸収剤で、高い光安定性を持ちます。",
    funFact: "BASFが開発した最新世代のUVA吸収剤です。",
  },
  {
    id: "bisoctrizole",
    nameJa: "ビスオクトリゾール",
    nameInci: "Methylene Bis-Benzotriazolyl Tetramethylbutylphenol",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "広いUV領域をカバーする紫外線吸収剤で、光安定性に非常に優れます。",
    funFact: "チバガイギー（現BASF）が開発したティノソーブMです。",
  },
  {
    id: "sodium-benzoate",
    nameJa: "安息香酸Na",
    nameInci: "Sodium Benzoate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "食品にも使われる防腐剤で、パラベンの代替として使用が増えています。",
    funFact: "クランベリーやプラムに天然に含まれる防腐成分です。",
  },
  {
    id: "potassium-sorbate",
    nameJa: "ソルビン酸K",
    nameInci: "Potassium Sorbate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "食品にも広く使われる防腐剤で、パラベンフリー製品に多く配合されます。",
    funFact: "ナナカマドの実から発見されたソルビン酸のカリウム塩です。",
  },
  {
    id: "acrylates-copolymer",
    nameJa: "アクリレーツコポリマー",
    nameInci: "Acrylates Copolymer",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "被膜形成・増粘剤として化粧品に配合されるポリマーです。",
  },
  {
    id: "ethanol",
    nameJa: "エタノール",
    nameInci: "Alcohol",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "溶剤・清浄剤・防腐補助として幅広く使われるアルコールです。",
    funFact: "化粧品表示では「アルコール」はエチルアルコールを指します。",
    caution: "高濃度では乾燥や刺激の原因になる場合があります。",
  },
  {
    id: "denatured-alcohol",
    nameJa: "変性アルコール",
    nameInci: "Alcohol Denat.",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "飲用できないよう変性処理されたアルコールです。",
    caution: "高濃度では乾燥を感じる場合があります。",
  },
  {
    id: "tocopheryl-acetate",
    nameJa: "酢酸トコフェロール",
    nameInci: "Tocopheryl Acetate",
    categories: ["brightening"],
    rarity: "common",
    genre: "vitamin",
    color: "#9CA3AF",
    note: "ビタミンEの安定化型で、整肌成分として配合されます。",
    funFact: "トコフェロールを酢酸エステル化して安定性を高めた成分です。",
  },
  {
    id: "bht",
    nameJa: "BHT",
    nameInci: "Butylated Hydroxytoluene",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "合成の酸化防止剤で、製品の酸化を防ぎます。",
  },
  {
    id: "edta-2na",
    nameJa: "EDTA-2Na",
    nameInci: "Disodium EDTA",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "キレート剤として金属イオンを捕捉し、製品の安定性を高めます。",
  },
  {
    id: "triethanolamine",
    nameJa: "トリエタノールアミン",
    nameInci: "Triethanolamine",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "pH調整剤・乳化剤として使われるアミン系化合物です。",
  },
  {
    id: "sodium-hydroxide-base",
    nameJa: "水酸化Na（pH調整）",
    nameInci: "Sodium Hydroxide",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "pH調整剤として微量使用される強アルカリです。",
  },
  {
    id: "potassium-hydroxide",
    nameJa: "水酸化K",
    nameInci: "Potassium Hydroxide",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "pH調整剤・石鹸の原料として使われるアルカリ成分です。",
    funFact: "液体石鹸はNaOHではなくKOHで作られます。",
  },
  {
    id: "glyceryl-stearate",
    nameJa: "ステアリン酸グリセリル",
    nameInci: "Glyceryl Stearate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "乳化剤として最も広く使われるグリセリン脂肪酸エステルです。",
  },
  {
    id: "sorbitan-oleate",
    nameJa: "ソルビタンオレイン酸エステル",
    nameInci: "Sorbitan Oleate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "W/O型（油中水型）乳化剤として使われるソルビタン脂肪酸エステルです。",
  },
  {
    id: "polysorbate-60",
    nameJa: "ポリソルベート60",
    nameInci: "Polysorbate 60",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "O/W型（水中油型）乳化剤として使われるポリオキシエチレンソルビタン脂肪酸エステルです。",
  },
  {
    id: "polysorbate-80",
    nameJa: "ポリソルベート80",
    nameInci: "Polysorbate 80",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "乳化・可溶化に広く使われる非イオン界面活性剤です。",
    funFact: "Tweenの商品名で知られ、医薬品にも使われるほど安全性が高い成分です。",
  },
  {
    id: "peg-100-stearate",
    nameJa: "PEG-100ステアレート",
    nameInci: "PEG-100 Stearate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "高HLBの非イオン乳化剤で、O/W型クリームに使われます。",
  },
  {
    id: "hydroxyethyl-acrylate",
    nameJa: "アクリル酸ヒドロキシエチルコポリマー",
    nameInci: "Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "ジェル状の増粘・乳化安定化ポリマーです。",
    funFact: "シメチコンフリーのジェルクリームによく使われるポリマーです。",
  },
  {
    id: "cellulose-gum",
    nameJa: "セルロースガム",
    nameInci: "Cellulose Gum",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "植物繊維由来の増粘安定剤で、テクスチャー調整に使われます。",
  },
  {
    id: "guar-gum",
    nameJa: "グアーガム",
    nameInci: "Guar Gum",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "グアー豆由来の天然増粘剤です。",
    funFact: "インド・パキスタン産のグアー豆から得られる多糖類です。",
  },
  {
    id: "methylcellulose",
    nameJa: "メチルセルロース",
    nameInci: "Methylcellulose",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "セルロースのメチルエーテルで、増粘・皮膜形成に使われます。",
  },
  {
    id: "allyl-methacrylates-crosspolymer",
    nameJa: "アクリレーツクロスポリマー",
    nameInci: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "カルボマーの変性型で、乳化安定化・増粘に使われるポリマーです。",
  },
  {
    id: "propylene-glycol",
    nameJa: "プロピレングリコール",
    nameInci: "Propylene Glycol",
    categories: ["moisturizing"],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "保湿・溶剤・防腐補助として使われる多機能成分です。",
    funFact: "PGとも呼ばれ、食品や医薬品にも広く使われる成分です。",
  },
  {
    id: "butyl-methoxydibenzoylmethane",
    nameJa: "ジエチルアミノヒドロキシベンゾイル安息香酸ヘキシル",
    nameInci: "Butyl Methoxydibenzoylmethane",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "Parsol 1789とも呼ばれるUVA吸収剤で、多くの日焼け止めに配合されます。",
    funFact: "アボベンゾンの化学名で、UVA防御の基本成分です。",
  },
  {
    id: "homosalate",
    nameJa: "ホモサレート",
    nameInci: "Homosalate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "UVB領域を吸収する紫外線吸収剤です。",
  },
  {
    id: "ethylhexyl-salicylate",
    nameJa: "サリチル酸エチルヘキシル",
    nameInci: "Ethylhexyl Salicylate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "UVB吸収剤で、オクチサレートとも呼ばれます。",
  },
  {
    id: "benzophenone-3",
    nameJa: "ベンゾフェノン-3",
    nameInci: "Benzophenone-3",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "オキシベンゾンとも呼ばれるUVA/UVB吸収剤です。",
    caution: "環境への影響が指摘されており、一部地域では使用が制限されています。",
  },
  {
    id: "ensulizole",
    nameJa: "フェニルベンゾイミダゾールスルホン酸",
    nameInci: "Phenylbenzimidazole Sulfonic Acid",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "水溶性のUVB吸収剤で、透明感のある日焼け止めに適しています。",
  },
  {
    id: "bis-ethylhexyloxyphenol-methoxyphenyl-triazine",
    nameJa: "ビスエチルヘキシルオキシフェノールメトキシフェニルトリアジン",
    nameInci: "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "ティノソーブSの化学名で、広いUV吸収スペクトルを持つ紫外線吸収剤です。",
    funFact: "UVA/UVBの両方をカバーする広帯域UV吸収剤の代表格です。",
  },
  {
    id: "polysilicone-15",
    nameJa: "ポリシリコーン-15",
    nameInci: "Polysilicone-15",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "シリコーン骨格にUV吸収基を組み込んだ紫外線吸収剤です。",
    funFact: "パーソルSQ（Parsol SQ）の商品名で知られる成分です。",
  },
  {
    id: "iron-oxides",
    nameJa: "酸化鉄",
    nameInci: "Iron Oxides",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "色材として広く使われる無機顔料で、赤・黄・黒の色を出します。",
    funFact: "可視光線やブルーライトも防御する効果があるとされています。",
  },
  {
    id: "silica",
    nameJa: "シリカ",
    nameInci: "Silica",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "吸着・マット化・テクスチャー調整に使われる無機粉体です。",
    funFact: "地球の地殻の約60%を構成する二酸化ケイ素です。",
  },
  {
    id: "mica",
    nameJa: "マイカ",
    nameInci: "Mica",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "天然の鉱物で、パール感や光沢を与える色材です。",
    funFact: "雲母とも呼ばれ、メイクアップ製品のキラキラ感の正体です。",
  },
  {
    id: "talc",
    nameJa: "タルク",
    nameInci: "Talc",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "最も柔らかい鉱物で、滑り感・吸着性を与える粉体基材です。",
    funFact: "モース硬度1の最も柔らかい鉱物です。",
  },
  {
    id: "cyclomethicone",
    nameJa: "シクロメチコン",
    nameInci: "Cyclomethicone",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "環状シリコーンで、軽いテクスチャーを与える揮発性の溶剤です。",
  },
  {
    id: "cyclopentasiloxane",
    nameJa: "シクロペンタシロキサン",
    nameInci: "Cyclopentasiloxane",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "揮発性の環状シリコーンで、サラッとした使用感を与えます。",
    funFact: "D5シリコーンとも呼ばれ、最も多用される揮発性シリコーンです。",
  },
  {
    id: "dimethicone-crosspolymer",
    nameJa: "ジメチコンクロスポリマー",
    nameInci: "Dimethicone Crosspolymer",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "シリコーン系の質感調整剤で、なめらかな使用感を与えます。",
    funFact: "シリコーンエラストマーとも呼ばれ、プライマーに多く使われます。",
  },
  {
    id: "cetearyl-glucoside",
    nameJa: "セテアリルグルコシド",
    nameInci: "Cetearyl Glucoside",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "糖由来の非イオン乳化剤で、肌にやさしいとされています。",
  },
  {
    id: "sodium-lauroyl-glutamate",
    nameJa: "ラウロイルグルタミン酸Na",
    nameInci: "Sodium Lauroyl Glutamate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "アミノ酸系の洗浄成分で、穏やかな洗浄力と泡立ちを持ちます。",
    funFact: "味の素が開発したアミノ酸系界面活性剤の代表格です。",
  },
  {
    id: "cocoyl-glutamate",
    nameJa: "ココイルグルタミン酸Na",
    nameInci: "Sodium Cocoyl Glutamate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "ヤシ油由来のアミノ酸系洗浄成分で、マイルドな洗浄成分として知られています。",
  },
  {
    id: "lauryl-glucoside",
    nameJa: "ラウリルグルコシド",
    nameInci: "Lauryl Glucoside",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "糖由来の非イオン洗浄成分で、やさしい洗い心地を目指す処方で使われます。",
  },
  {
    id: "coco-glucoside",
    nameJa: "ココグルコシド",
    nameInci: "Coco-Glucoside",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "ヤシ油と糖から作られる天然由来の洗浄成分です。",
  },
  {
    id: "sodium-cocoyl-isethionate",
    nameJa: "ココイルイセチオン酸Na",
    nameInci: "Sodium Cocoyl Isethionate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "マイルドな洗浄力の合成界面活性剤で、固形石鹸にも使われます。",
    funFact: "「ベビーマイルド」と呼ばれるほど穏やかな洗浄成分です。",
  },
  {
    id: "decyl-glucoside",
    nameJa: "デシルグルコシド",
    nameInci: "Decyl Glucoside",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "植物由来の非イオン洗浄成分で、マイルドな洗浄料に配合されます。",
  },
  {
    id: "sles",
    nameJa: "ラウレス硫酸Na",
    nameInci: "Sodium Laureth Sulfate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "最も広く使われる陰イオン洗浄成分の一つです。",
    funFact: "SLESと略され、シャンプーや洗顔料の基本洗浄成分です。",
  },
  {
    id: "sls",
    nameJa: "ラウリル硫酸Na",
    nameInci: "Sodium Lauryl Sulfate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "強い洗浄力を持つ陰イオン界面活性剤です。",
    caution: "洗浄力が強いため、敏感肌の方には刺激になる場合があります。",
  },
  {
    id: "water",
    nameJa: "水",
    nameInci: "Water",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "ほぼすべての化粧品の基材となる最も基本的な成分です。",
    funFact: "化粧品の成分表示で最初に記載されることが最も多い成分です。",
  },
  {
    id: "isododecane",
    nameJa: "イソドデカン",
    nameInci: "Isododecane",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "揮発性の炭化水素で、軽い使用感の溶剤として使われます。",
  },
  {
    id: "isohexadecane",
    nameJa: "イソヘキサデカン",
    nameInci: "Isohexadecane",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "エモリエント・溶剤として使われる炭化水素オイルです。",
  },
  {
    id: "c12-15-alkyl-benzoate",
    nameJa: "安息香酸アルキル（C12-15）",
    nameInci: "C12-15 Alkyl Benzoate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "軽いテクスチャーのエモリエント・溶剤で、UV吸収剤の溶解にも使われます。",
  },
  {
    id: "cetyl-peg-ppg-dimethicone",
    nameJa: "セチルPEG/PPG-10/1ジメチコン",
    nameInci: "Cetyl PEG/PPG-10/1 Dimethicone",
    categories: [],
    rarity: "uncommon",
    genre: "base",
    color: "#9CA3AF",
    note: "シリコーン系の乳化剤で、W/O型エマルジョンに使われます。",
  },
  {
    id: "pentaerythrityl-tetraethylhexanoate",
    nameJa: "テトラエチルヘキサン酸ペンタエリスリチル",
    nameInci: "Pentaerythrityl Tetraethylhexanoate",
    categories: [],
    rarity: "common",
    genre: "base",
    color: "#9CA3AF",
    note: "合成エステル油で、のびが良く軽いテクスチャーを与えます。",
  },

  // ─── 追加: 発酵系 ─────────────────────────────────────────
  {
    id: "saccharomyces-ferment-filtrate",
    nameJa: "サッカロミセス培養液",
    nameInci: "Saccharomyces Ferment Filtrate",
    categories: ["moisturizing", "brightening"],
    rarity: "rare",
    genre: "ferment",
    color: "#4FC3F7",
    note: "酵母を発酵させて得られる培養液で、保湿・整肌に優れた発酵成分です。",
    funFact: "SK-IIのピテラとして世界的に知られる発酵成分です。",
  },
  {
    id: "aspergillus-ferment",
    nameJa: "コウジ菌発酵エキス",
    nameInci: "Aspergillus Ferment",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "ferment",
    color: "#CE93D8",
    note: "麹菌を発酵して得られるエキスで、整肌目的で配合されます。",
    funFact: "日本の発酵文化を活かした和コスメの代表的成分です。",
  },
  {
    id: "bacillus-ferment",
    nameJa: "バチルス発酵液",
    nameInci: "Bacillus Ferment",
    categories: ["keratin"],
    rarity: "uncommon",
    genre: "ferment",
    color: "#90A4AE",
    note: "納豆菌などバチルス属の発酵液で、角質ケア系の製品に使われることがあります。",
    funFact: "納豆菌の酵素力を活かした日本発の角質ケア成分です。",
  },
  {
    id: "lactococcus-ferment-lysate",
    nameJa: "ラクトコッカス溶解液",
    nameInci: "Lactococcus Ferment Lysate",
    categories: ["soothing", "barrier"],
    rarity: "uncommon",
    genre: "ferment",
    color: "#80CBC4",
    note: "乳酸球菌由来の発酵・溶解物で、整肌目的で配合されることがある成分です。",
    funFact: "発酵由来成分として、バイオーム系コスメで取り上げられることがあります。",
  },
  {
    id: "pichia-anomala-ferment",
    nameJa: "異常酵母発酵液",
    nameInci: "Pichia Anomala Extract",
    categories: ["barrier", "moisturizing"],
    rarity: "rare",
    genre: "ferment",
    color: "#81C784",
    note: "酵母由来の発酵成分で、整肌・保湿目的で配合されることがあります。",
    funFact: "発酵由来のバイオーム系コスメで見かけることがある成分です。",
  },

  // ─── 追加: その他の機能性成分 ─────────────────────────────
  {
    id: "coq10",
    nameJa: "コエンザイムQ10（補酵素Q10）",
    nameInci: "Ubiquinone",
    categories: ["brightening", "turnover"],
    rarity: "rare",
    genre: "vitamin",
    color: "#FFB74D",
    note: "細胞のエネルギー産生に関わる補酵素で、DHCの人気成分として知られます。",
    funFact: "日本ではDHCが先駆けとなり、CoQ10配合コスメが大ブームとなりました。",
  },
  {
    id: "ceramide-complex",
    nameJa: "セラミドコンプレックス",
    nameInci: "Ceramide Complex",
    categories: ["barrier"],
    rarity: "uncommon",
    genre: "oil_lipid",
    color: "#81C784",
    note: "複数のセラミドを組み合わせた複合バリア成分です。",
    funFact: "角質層には12種類以上のセラミドが存在するとされています。",
  },
  {
    id: "palmitoyl-glycine",
    nameJa: "パルミトイルグリシン",
    nameInci: "Palmitoyl Glycine",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "peptide",
    color: "#80CBC4",
    note: "グリシンと脂肪酸のエステルで、整肌目的で配合される成分です。",
  },
  {
    id: "succinic-acid",
    nameJa: "コハク酸",
    nameInci: "Succinic Acid",
    categories: ["keratin"],
    rarity: "common",
    genre: "acid",
    color: "#90A4AE",
    note: "琥珀から発見された有機酸で、角質ケア目的で配合されることがあります。",
    funFact: "名前の由来はラテン語の「succinum（琥珀）」です。",
  },
  {
    id: "zinc-pca",
    nameJa: "PCA亜鉛",
    nameInci: "Zinc PCA",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#80CBC4",
    note: "亜鉛とピロリドンカルボン酸の塩で、整肌成分として使われます。",
    funFact: "脂性肌向け製品で見かけることがある成分です。",
  },
  {
    id: "niacinamide-high",
    nameJa: "ナイアシンアミド（高濃度）",
    nameInci: "Niacinamide",
    categories: ["brightening", "barrier", "turnover"],
    rarity: "rare",
    genre: "vitamin",
    color: "#CE93D8",
    note: "高濃度配合のナイアシンアミドで、整肌成分として注目されることがあります。",
    funFact: "10%以上の高濃度配合製品も見られます。",
  },
  {
    id: "vitamin-k",
    nameJa: "ビタミンK",
    nameInci: "Phytonadione",
    categories: ["soothing"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#80CBC4",
    note: "脂溶性ビタミンで、目元用製品などに配合されることがある成分です。",
    funFact: "血液凝固（Koagulation）に関わるため「K」と名付けられました。",
  },
  {
    id: "biotin",
    nameJa: "ビオチン",
    nameInci: "Biotin",
    categories: ["moisturizing"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#4FC3F7",
    note: "ビタミンB7とも呼ばれ、皮膚や毛髪の健康維持に関わる水溶性ビタミンです。",
    funFact: "「bios（生命）」に由来する名前で、ビタミンHとも呼ばれます。",
  },
  {
    id: "pantothenic-acid",
    nameJa: "パントテン酸",
    nameInci: "Pantothenic Acid",
    categories: ["moisturizing", "soothing"],
    rarity: "common",
    genre: "acid",
    color: "#4FC3F7",
    note: "ビタミンB5で、パンテノールが体内で変換された活性型です。",
    funFact: "ギリシャ語の「pantos（すべて）」に由来し、あらゆる食物に含まれます。",
  },
  {
    id: "menthol",
    nameJa: "メントール",
    nameInci: "Menthol",
    categories: [],
    rarity: "common",
    genre: "botanical",
    color: "#9CA3AF",
    note: "ミントから得られるテルペンアルコールで、清涼感を与える成分です。",
    funFact: "実際に温度を下げるのではなく、冷感受容体を活性化して清涼感を生みます。",
  },
  {
    id: "camphor",
    nameJa: "カンフル",
    nameInci: "Camphor",
    categories: [],
    rarity: "common",
    genre: "botanical",
    color: "#9CA3AF",
    note: "クスノキから得られるテルペンケトンで、清涼感を与える成分として使われます。",
    funFact: "樟脳（しょうのう）として防虫剤にも使われる歴史ある成分です。",
  },
  {
    id: "sodium-ascorbate",
    nameJa: "アスコルビン酸Na",
    nameInci: "Sodium Ascorbate",
    categories: ["brightening"],
    rarity: "uncommon",
    genre: "vitamin",
    color: "#CE93D8",
    note: "ビタミンCのナトリウム塩で、安定性が向上した整肌成分です。",
  },
  {
    id: "retinol-binding-protein",
    nameJa: "レチノール結合タンパク質",
    nameInci: "Retinol Binding Protein",
    categories: ["turnover"],
    rarity: "rare",
    genre: "vitamin",
    color: "#FFB74D",
    note: "レチノールの運搬に関わるタンパク質で、レチノールの安定供給をサポートします。",
  },
  {
    id: "astaxanthin-complex",
    nameJa: "アスタキサンチンコンプレックス",
    nameInci: "Haematococcus Pluvialis Extract",
    categories: ["brightening", "turnover"],
    rarity: "legendary",
    genre: "base",
    color: "#F59E0B",
    note: "ヘマトコッカス藻から得られるアスタキサンチン高含有エキスです。",
    funFact: "ヘマトコッカス藻は過酷な環境でアスタキサンチンを大量に蓄積します。",
  },
  {
    id: "soybean-extract",
    nameJa: "ダイズエキス",
    nameInci: "Glycine Soja Seed Extract",
    categories: ["brightening", "moisturizing"],
    rarity: "common",
    genre: "botanical",
    color: "#CE93D8",
    note: "大豆由来のエキスで、イソフラボンを含む整肌・保湿成分です。",
    funFact: "大豆イソフラボンは植物性エストロゲンとして知られています。",
  },
  {
    id: "sake-lees-extract",
    nameJa: "酒粕エキス",
    nameInci: "Sake Lees Extract",
    categories: ["brightening", "moisturizing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "日本酒の酒粕から得られる発酵エキスで、整肌・保湿目的で配合されます。",
    funFact: "酒粕由来の発酵美容素材として紹介されることのある成分です。",
  },
  {
    id: "pearl-extract",
    nameJa: "真珠エキス",
    nameInci: "Conchiolin",
    categories: ["brightening", "moisturizing"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#CE93D8",
    note: "真珠の主要タンパク質コンキオリンを含むエキスで、整肌・保湿目的で配合されます。",
    funFact: "クレオパトラが真珠を酢に溶かして飲んでいたという伝説があります。",
  },
  {
    id: "yuzu-extract",
    nameJa: "ユズ果実エキス",
    nameInci: "Citrus Junos Fruit Extract",
    categories: ["moisturizing", "brightening"],
    rarity: "uncommon",
    genre: "botanical",
    color: "#4FC3F7",
    note: "高知県産のユズから得られるエキスで、整肌・保湿目的で配合されます。",
    funFact: "ユズの種にはペクチンが含まれます。",
  },
  {
    id: "rice-ferment-filtrate",
    nameJa: "コメ発酵液",
    nameInci: "Oryza Sativa Ferment Filtrate",
    categories: ["moisturizing", "brightening"],
    rarity: "uncommon",
    genre: "ferment",
    color: "#4FC3F7",
    note: "米を発酵させて得られる培養液で、日本の発酵文化を活かした成分です。",
    funFact: "日本酒の醸造過程から着想を得た美容成分です。",
  },
];

// O(1) lookup maps（線形検索を排除）
const _byId = new Map(MASTER_INGREDIENTS.map((i) => [i.id, i]));
const _byName = new Map(MASTER_INGREDIENTS.map((i) => [i.nameJa, i]));

export function getIngredientById(id: string): Ingredient | undefined {
  return _byId.get(id);
}

export function getIngredientByName(nameJa: string): Ingredient | undefined {
  return _byName.get(nameJa);
}
