import { Ingredient, RarityKey, RarityInfo } from "@/types";

export const RARITY: Record<RarityKey, RarityInfo> = {
  common:    { label: "コモン",       star: 1, color: "#9CA3AF", icon: "🫧" },
  uncommon:  { label: "アンコモン",   star: 2, color: "#2D9CDB", icon: "🧪" },
  rare:      { label: "レア",         star: 3, color: "#7C6AE8", icon: "🔮" },
  legendary: { label: "レジェンダリー", star: 4, color: "#F59E0B", icon: "💎" },
};

export const MASTER_INGREDIENTS: Ingredient[] = [
  // ─── 整肌系 ───────────────────────────────────────────────
  {
    id: "niacinamide",
    nameJa: "ナイアシンアミド",
    nameInci: "Niacinamide",
    categories: ["brightening", "barrier", "moisturizing"],
    rarity: "common",
    color: "#CE93D8",
    note: "ビタミンB3の一種で、多くのスキンケア製品に配合される成分です。",
    funFact: "ビタミンB3は水溶性ビタミンで、体内で補酵素NADの前駆体として働きます。",
  },
  {
    id: "arbutin",
    nameJa: "アルブチン",
    nameInci: "Arbutin",
    categories: ["brightening"],
    rarity: "rare",
    color: "#7C6AE8",
    note: "コケモモなどに含まれる整肌系の成分です。",
    funFact: "1989年に日本で医薬部外品の有効成分として承認されました。",
  },
  {
    id: "alpha-arbutin",
    nameJa: "α-アルブチン",
    nameInci: "Alpha-Arbutin",
    categories: ["brightening"],
    rarity: "rare",
    color: "#7C6AE8",
    note: "通常のアルブチンより安定性が高く、整肌系成分として注目されています。",
    funFact: "α型はβ型（アルブチン）と比べて安定性・効果が高いとされています。",
  },
  {
    id: "tranexamic-acid",
    nameJa: "トラネキサム酸",
    nameInci: "Tranexamic Acid",
    categories: ["brightening", "soothing"],
    rarity: "rare",
    color: "#CE93D8",
    note: "医薬品として使われてきた成分で、整肌・鎮静系として化粧品にも配合されます。",
    funFact: "もともと止血剤として開発されましたが、肌への作用も発見されました。",
  },
  {
    id: "ascorbic-acid",
    nameJa: "アスコルビン酸",
    nameInci: "Ascorbic Acid",
    categories: ["brightening", "turnover"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "ビタミンCそのもので、整肌系・ハリ系に分類される成分です。",
    funFact: "壊血病の予防として発見された歴史があります。",
    caution: "酸化しやすいため、保存方法に注意が必要な成分です。",
  },
  {
    id: "ascorbyl-glucoside",
    nameJa: "アスコルビルグルコシド",
    nameInci: "Ascorbyl Glucoside",
    categories: ["brightening"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "ビタミンCにグルコースを結合させた安定型ビタミンC誘導体です。",
    funFact: "水に溶けやすく酸化しにくいため、扱いやすいビタミンC誘導体です。",
  },
  {
    id: "ethyl-ascorbic-acid",
    nameJa: "3-O-エチルアスコルビン酸",
    nameInci: "3-O-Ethyl Ascorbic Acid",
    categories: ["brightening"],
    rarity: "rare",
    color: "#CE93D8",
    note: "高い安定性と浸透性を持つビタミンC誘導体です。",
    funFact: "油溶性と水溶性の両方の性質を持つ両親媒性の成分です。",
  },
  {
    id: "sodium-ascorbyl-phosphate",
    nameJa: "アスコルビルリン酸Na",
    nameInci: "Sodium Ascorbyl Phosphate",
    categories: ["brightening"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "水溶性の安定型ビタミンC誘導体で、幅広い製品に配合されます。",
  },
  {
    id: "tocopherol",
    nameJa: "トコフェロール",
    nameInci: "Tocopherol",
    categories: ["brightening"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "ビタミンEの一種で、整肌系に分類される成分です。",
    funFact: "「子供を産む」を意味するギリシャ語が名前の由来です。",
  },
  {
    id: "kojic-acid",
    nameJa: "コウジ酸",
    nameInci: "Kojic Acid",
    categories: ["brightening"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "麹菌が産生する有機酸で、日本酒の醸造過程で発見された整肌成分です。",
    funFact: "麹（こうじ）からその名が付いています。",
  },
  {
    id: "astaxanthin",
    nameJa: "アスタキサンチン",
    nameInci: "Astaxanthin",
    categories: ["brightening", "barrier"],
    rarity: "legendary",
    color: "#F59E0B",
    note: "カロテノイドの一種で、整肌・バリア系に分類される希少成分です。",
    funFact: "サケやエビの赤色の元となる天然色素です。",
  },
  {
    id: "fullerene",
    nameJa: "フラーレン",
    nameInci: "Fullerene",
    categories: ["brightening"],
    rarity: "legendary",
    color: "#F59E0B",
    note: "炭素原子60個で構成される球状分子で、高い整肌機能を持つ希少成分です。",
    funFact: "1985年に発見され、発見者はノーベル化学賞を受賞しました。",
  },
  {
    id: "resveratrol",
    nameJa: "レスベラトロール",
    nameInci: "Resveratrol",
    categories: ["brightening", "soothing"],
    rarity: "rare",
    color: "#CE93D8",
    note: "赤ワインやブドウの皮に含まれるポリフェノールの一種です。",
    funFact: "フランスのパラドックスを説明する成分として研究が進みました。",
  },
  {
    id: "ubiquinone",
    nameJa: "ユビキノン",
    nameInci: "Ubiquinone",
    categories: ["brightening"],
    rarity: "rare",
    color: "#CE93D8",
    note: "CoQ10（コエンザイムQ10）とも呼ばれる整肌系成分です。",
    funFact: "細胞のエネルギー産生に関わる補酵素として体内にも存在します。",
  },

  // ─── ハリ・弾力系 ─────────────────────────────────────────
  {
    id: "retinol",
    nameJa: "レチノール",
    nameInci: "Retinol",
    categories: ["turnover"],
    rarity: "rare",
    color: "#FFB74D",
    note: "ビタミンAの一種で、ハリ・弾力系に分類される成分です。",
    funFact: "レチノールは1909年に発見された最初のビタミンです。",
    caution: "光に不安定なため、夜間の使用が一般的です。使い始めは少量からが推奨されます。",
  },
  {
    id: "retinal",
    nameJa: "レチナール",
    nameInci: "Retinal",
    categories: ["turnover"],
    rarity: "legendary",
    color: "#F59E0B",
    note: "レチノールよりも1段階変換が少ない高活性型ビタミンA誘導体です。",
    funFact: "目の網膜（retina）にも存在し、光を感知する役割を持ちます。",
    caution: "高い活性を持つため、使い始めは低濃度・低頻度から始めることが推奨されます。",
  },
  {
    id: "retinyl-palmitate",
    nameJa: "レチニルパルミテート",
    nameInci: "Retinyl Palmitate",
    categories: ["turnover"],
    rarity: "uncommon",
    color: "#FFB74D",
    note: "パルミチン酸とレチノールのエステルで、比較的穏やかなビタミンA誘導体です。",
    funFact: "食品にも使われる安全性の高いビタミンA誘導体の一つです。",
  },
  {
    id: "hydroxypinacolone-retinoate",
    nameJa: "ヒドロキシピナコロンレチノエート",
    nameInci: "Hydroxypinacolone Retinoate",
    categories: ["turnover"],
    rarity: "rare",
    color: "#FFB74D",
    note: "レチノイン酸エステルで、低刺激性のビタミンA誘導体として注目されています。",
    funFact: "レチノール変換を必要とせず直接レチノイン酸受容体に結合します。",
  },
  {
    id: "bakuchiol",
    nameJa: "バクチオール",
    nameInci: "Bakuchiol",
    categories: ["turnover"],
    rarity: "rare",
    color: "#FFB74D",
    note: "植物由来のハリ・弾力系成分で、レチノールの代替として注目されています。",
    funFact: "インドの伝統医学アーユルヴェーダで古くから使われてきた植物由来です。",
  },
  {
    id: "peptide",
    nameJa: "ペプチド",
    nameInci: "Palmitoyl Tripeptide-1",
    categories: ["turnover", "barrier"],
    rarity: "legendary",
    color: "#F59E0B",
    note: "アミノ酸が結合した成分で、ハリ・弾力系・バリア系に分類される希少成分です。",
    funFact: "ペプチドは「消化する」を意味するギリシャ語が語源です。",
  },
  {
    id: "acetyl-hexapeptide-3",
    nameJa: "アセチルヘキサペプチド-3",
    nameInci: "Acetyl Hexapeptide-3",
    categories: ["turnover"],
    rarity: "legendary",
    color: "#F59E0B",
    note: "アルジレリンとも呼ばれる6つのアミノ酸からなるペプチド成分です。",
    funFact: "神経伝達物質の作用に着目して開発されたペプチドです。",
  },
  {
    id: "copper-tripeptide-1",
    nameJa: "銅トリペプチド-1",
    nameInci: "Copper Tripeptide-1",
    categories: ["turnover", "barrier"],
    rarity: "legendary",
    color: "#F59E0B",
    note: "銅イオンと3つのアミノ酸が結合したペプチドで、ハリ・バリア系の希少成分です。",
    funFact: "1970年代に血漿中で発見された生体由来のペプチドです。",
  },
  {
    id: "adenosine",
    nameJa: "アデノシン",
    nameInci: "Adenosine",
    categories: ["turnover"],
    rarity: "rare",
    color: "#FFB74D",
    note: "細胞のエネルギー通貨ATPの構成成分で、ハリ・弾力系成分として配合されます。",
    funFact: "韓国食品医薬品安全処（MFDS）で機能性成分として認可されています。",
  },
  {
    id: "hydrolyzed-collagen",
    nameJa: "加水分解コラーゲン",
    nameInci: "Hydrolyzed Collagen",
    categories: ["moisturizing", "turnover"],
    rarity: "uncommon",
    color: "#4FC3F7",
    note: "コラーゲンを加水分解して低分子化した保湿・ハリ系成分です。",
    funFact: "肌の真皮層の約70%はコラーゲンで構成されています。",
  },
  {
    id: "hydrolyzed-elastin",
    nameJa: "加水分解エラスチン",
    nameInci: "Hydrolyzed Elastin",
    categories: ["moisturizing", "turnover"],
    rarity: "uncommon",
    color: "#4FC3F7",
    note: "エラスチンを加水分解した保湿・弾力系成分です。",
    funFact: "エラスチンはゴムのような弾性を持ち、肌の弾力を支えています。",
  },

  // ─── 保湿系 ────────────────────────────────────────────────
  {
    id: "sodium-hyaluronate",
    nameJa: "ヒアルロン酸Na",
    nameInci: "Sodium Hyaluronate",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "高い保水力を持つ保湿成分として広く知られています。",
    funFact: "1gで約6リットルの水分を保持できると言われています。",
  },
  {
    id: "acetylated-hyaluronate",
    nameJa: "アセチル化ヒアルロン酸Na",
    nameInci: "Sodium Acetylated Hyaluronate",
    categories: ["moisturizing"],
    rarity: "rare",
    color: "#4FC3F7",
    note: "通常のヒアルロン酸Naよりも油溶性が高まり、肌表面に留まりやすい高機能保湿成分です。",
    funFact: "スーパーヒアルロン酸とも呼ばれ、通常の2倍の保湿力があるとも言われます。",
  },
  {
    id: "hydrolyzed-hyaluronate",
    nameJa: "加水分解ヒアルロン酸",
    nameInci: "Hydrolyzed Hyaluronic Acid",
    categories: ["moisturizing"],
    rarity: "uncommon",
    color: "#4FC3F7",
    note: "ヒアルロン酸を加水分解して低分子化した保湿成分です。",
    funFact: "分子が小さいため肌深部への浸透性が高いとされています。",
  },
  {
    id: "sodium-polyglutamate",
    nameJa: "ポリグルタミン酸Na",
    nameInci: "Sodium Polyglutamate",
    categories: ["moisturizing"],
    rarity: "uncommon",
    color: "#4FC3F7",
    note: "納豆の糸に含まれる天然のポリアミノ酸で、高い保湿力を持ちます。",
    funFact: "納豆菌が産生するネバネバの成分がこのポリグルタミン酸です。",
  },
  {
    id: "glycerin",
    nameJa: "グリセリン",
    nameInci: "Glycerin",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "最も基本的な保湿成分の一つで、多くの化粧品に配合されています。",
    funFact: "食品にも使われる安全性の高い成分です。",
  },
  {
    id: "bg",
    nameJa: "BG",
    nameInci: "Butylene Glycol",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "ブチレングリコールとも呼ばれる保湿・溶剤成分で、ほぼすべての化粧品に配合されます。",
    funFact: "保湿だけでなく防腐補助剤としても機能します。",
  },
  {
    id: "pentylene-glycol",
    nameJa: "ペンチレングリコール",
    nameInci: "Pentylene Glycol",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "植物由来の保湿成分で、防腐補助効果も持ちます。",
    funFact: "天然のサトウキビなどから得られる成分です。",
  },
  {
    id: "diglycerin",
    nameJa: "ジグリセリン",
    nameInci: "Diglycerin",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "グリセリンが2分子結合した保湿成分で、グリセリンより粘度が低いです。",
  },
  {
    id: "sorbitol",
    nameJa: "ソルビトール",
    nameInci: "Sorbitol",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "果物に含まれる天然の糖アルコールで、穏やかな保湿作用があります。",
    funFact: "リンゴやナシなどの果物に天然に含まれています。",
  },
  {
    id: "trehalose",
    nameJa: "トレハロース",
    nameInci: "Trehalose",
    categories: ["moisturizing"],
    rarity: "uncommon",
    color: "#4FC3F7",
    note: "2分子のグルコースからなる二糖類の保湿成分です。",
    funFact: "乾燥に強い生物（クマムシ等）が体内に蓄える糖として知られています。",
  },
  {
    id: "betaine",
    nameJa: "ベタイン",
    nameInci: "Betaine",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "砂糖大根に含まれる天然の保湿成分で、肌をしっとりさせます。",
    funFact: "テンサイ（砂糖大根）から発見された成分で、「ビート」が名前の由来です。",
  },
  {
    id: "squalane",
    nameJa: "スクワラン",
    nameInci: "Squalane",
    categories: ["moisturizing", "barrier"],
    rarity: "uncommon",
    color: "#81C784",
    note: "もともと人の皮脂にも含まれる成分で、なじみの良いオイル成分です。",
    funFact: "かつてはサメの肝油から得られていましたが、現在は植物由来が主流です。",
  },
  {
    id: "shea-butter",
    nameJa: "シア脂",
    nameInci: "Butyrospermum Parkii Butter",
    categories: ["moisturizing", "barrier"],
    rarity: "uncommon",
    color: "#81C784",
    note: "アフリカ産シアの木の実から得られる天然の植物性バターです。",
    funFact: "西アフリカでは「生命の木」と呼ばれ、何世紀も使われてきた成分です。",
  },
  {
    id: "jojoba-oil",
    nameJa: "ホホバ種子油",
    nameInci: "Simmondsia Chinensis Seed Oil",
    categories: ["moisturizing", "barrier"],
    rarity: "uncommon",
    color: "#81C784",
    note: "ホホバの種子から得られる植物性ワックスエステルで、人の皮脂に近い成分です。",
    funFact: "植物油ではなくワックスエステルに分類され、酸化しにくい特性があります。",
  },
  {
    id: "caprylic-capric-triglyceride",
    nameJa: "カプリル酸/カプリン酸トリグリセリル",
    nameInci: "Caprylic/Capric Triglyceride",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "ヤシ油・パーム核油由来のエモリエント成分で、のびの良いテクスチャーを与えます。",
    funFact: "MCTオイルとも呼ばれ、食品としても使われます。",
  },
  {
    id: "dimethicone",
    nameJa: "ジメチコン",
    nameInci: "Dimethicone",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#9CA3AF",
    note: "シリコーン系のエモリエント成分で、なめらかさとのびの良さを与えます。",
    funFact: "シリコーン樹脂の一種で、医療機器にも使われるほど安全性が高い成分です。",
  },
  {
    id: "cetyl-alcohol",
    nameJa: "セタノール",
    nameInci: "Cetyl Alcohol",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#9CA3AF",
    note: "高級アルコールの一種で、エモリエント・乳化補助として配合されます。",
    funFact: "名前に「アルコール」とありますが、肌を乾燥させるアルコールとは別の成分です。",
  },
  {
    id: "stearyl-alcohol",
    nameJa: "ステアリルアルコール",
    nameInci: "Stearyl Alcohol",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#9CA3AF",
    note: "高級脂肪アルコールで、クリームやローションの質感調整に使われます。",
  },
  {
    id: "cetearyl-alcohol",
    nameJa: "セテアリルアルコール",
    nameInci: "Cetearyl Alcohol",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#9CA3AF",
    note: "セタノールとステアリルアルコールの混合物で、乳化・エモリエントに使われます。",
  },
  {
    id: "isopropyl-myristate",
    nameJa: "ミリスチン酸イソプロピル",
    nameInci: "Isopropyl Myristate",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#9CA3AF",
    note: "軽いテクスチャーのエモリエント成分で、のびの良さを与えます。",
  },
  {
    id: "aloe-vera",
    nameJa: "アロエベラ液汁",
    nameInci: "Aloe Barbadensis Leaf Juice",
    categories: ["moisturizing", "soothing"],
    rarity: "common",
    color: "#80CBC4",
    note: "アロエベラの葉から得られる液汁で、保湿・鎮静作用があります。",
    funFact: "「万能薬」とも呼ばれ、エジプトのパピルスにも記述がある歴史ある成分です。",
  },
  {
    id: "panthenol",
    nameJa: "パンテノール",
    nameInci: "Panthenol",
    categories: ["moisturizing", "soothing"],
    rarity: "common",
    color: "#80CBC4",
    note: "プロビタミンB5とも呼ばれ、保湿・鎮静効果を持つ汎用性の高い成分です。",
    funFact: "皮膚でパントテン酸（ビタミンB5）に変換されます。",
  },
  {
    id: "polyquaternium-51",
    nameJa: "ポリクオタニウム-51",
    nameInci: "Polyquaternium-51",
    categories: ["moisturizing", "barrier"],
    rarity: "rare",
    color: "#4FC3F7",
    note: "細胞膜に似た構造を持つ擬似セラミド型の保湿成分です。",
    funFact: "「リピジュア」の商品名でも知られる、日本発の成分です。",
  },
  {
    id: "hydrolyzed-silk",
    nameJa: "加水分解シルク",
    nameInci: "Hydrolyzed Silk",
    categories: ["moisturizing"],
    rarity: "rare",
    color: "#4FC3F7",
    note: "シルクを加水分解したタンパク質成分で、なめらかさと保湿効果を与えます。",
    funFact: "シルクはセリシンとフィブロインという2種類のタンパク質でできています。",
  },
  {
    id: "arginine",
    nameJa: "アルギニン",
    nameInci: "Arginine",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "アミノ酸の一種で、保湿と肌コンディショニングに役立ちます。",
    funFact: "ヒトの体内で合成される半必須アミノ酸です。",
  },
  {
    id: "glycine",
    nameJa: "グリシン",
    nameInci: "Glycine",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "最もシンプルなアミノ酸で、保湿成分として配合されます。",
    funFact: "コラーゲンの約3分の1がグリシン残基で構成されています。",
  },
  {
    id: "serine",
    nameJa: "セリン",
    nameInci: "Serine",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "天然保湿因子（NMF）の構成成分の一つであるアミノ酸です。",
    funFact: "NMFの約18%を占めるアミノ酸成分です。",
  },
  {
    id: "proline",
    nameJa: "プロリン",
    nameInci: "Proline",
    categories: ["moisturizing", "turnover"],
    rarity: "common",
    color: "#4FC3F7",
    note: "コラーゲンに多く含まれるアミノ酸で、保湿とハリ系の両面に関わります。",
    funFact: "コラーゲンの約13%がプロリン残基で構成されています。",
  },

  // ─── バリア系 ──────────────────────────────────────────────
  {
    id: "ceramide-np",
    nameJa: "セラミドNP",
    nameInci: "Ceramide NP",
    categories: ["barrier", "moisturizing"],
    rarity: "rare",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種です。",
    funFact: "ヒトの角質層に存在する細胞間脂質の主成分です。",
  },
  {
    id: "ceramide-eop",
    nameJa: "セラミドEOP",
    nameInci: "Ceramide EOP",
    categories: ["barrier"],
    rarity: "rare",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種で、長鎖脂肪酸を持ちます。",
    funFact: "セラミドEOPは「E」がエステル型、「O」がオレイン酸、「P」がフィトスフィンゴシン骨格を意味します。",
  },
  {
    id: "ceramide-ap",
    nameJa: "セラミドAP",
    nameInci: "Ceramide AP",
    categories: ["barrier"],
    rarity: "rare",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種です。",
  },
  {
    id: "ceramide-eos",
    nameJa: "セラミドEOS",
    nameInci: "Ceramide EOS",
    categories: ["barrier"],
    rarity: "rare",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種です。",
  },
  {
    id: "ceramide-ng",
    nameJa: "セラミドNG",
    nameInci: "Ceramide NG",
    categories: ["barrier"],
    rarity: "rare",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種で、多くのバリア修復製品に配合されます。",
  },
  {
    id: "phytosphingosine",
    nameJa: "フィトスフィンゴシン",
    nameInci: "Phytosphingosine",
    categories: ["barrier", "soothing"],
    rarity: "rare",
    color: "#81C784",
    note: "セラミドの前駆体となるスフィンゴイド塩基で、バリア機能と鎮静作用があります。",
    funFact: "酵母から発酵生産される天然由来の成分です。",
  },
  {
    id: "cholesterol",
    nameJa: "コレステロール",
    nameInci: "Cholesterol",
    categories: ["barrier"],
    rarity: "uncommon",
    color: "#81C784",
    note: "肌の細胞間脂質の構成成分の一つで、セラミドとともにバリア機能を担います。",
    funFact: "皮膚のバリア機能にはセラミド・コレステロール・脂肪酸の3成分が重要です。",
  },
  {
    id: "cica",
    nameJa: "CICA",
    nameInci: "Centella Asiatica",
    categories: ["soothing", "barrier"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "ツボクサ由来の成分で、鎮静・バリア系に分類されます。",
    funFact: "韓国スキンケアブームで世界的に注目された成分です。",
  },
  {
    id: "centella-asiatica-extract",
    nameJa: "ツボクサエキス",
    nameInci: "Centella Asiatica Extract",
    categories: ["soothing", "barrier"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "ツボクサから得られるエキスで、鎮静・バリア強化作用があります。",
    funFact: "アジア圏の伝統医学で古くから傷の治癒に使われてきた植物です。",
  },

  // ─── 鎮静系 ────────────────────────────────────────────────
  {
    id: "allantoin",
    nameJa: "アラントイン",
    nameInci: "Allantoin",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "肌荒れ防止に分類される鎮静系の成分です。",
    funFact: "コンフリー（ヒレハリソウ）の根から発見された成分です。",
  },
  {
    id: "dipotassium-glycyrrhizate",
    nameJa: "グリチルリチン酸2K",
    nameInci: "Dipotassium Glycyrrhizate",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "甘草に含まれる成分で、医薬部外品の有効成分にも指定されている鎮静成分です。",
    funFact: "甘草は漢方でも広く使われ、その甘味成分がグリチルリチン酸です。",
  },
  {
    id: "stearyl-glycyrrhetinate",
    nameJa: "グリチルレチン酸ステアリル",
    nameInci: "Stearyl Glycyrrhetinate",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "グリチルリチン酸の誘導体で、油溶性の鎮静成分です。",
    funFact: "医薬部外品の有効成分として認められている成分です。",
  },
  {
    id: "bisabolol",
    nameJa: "ビサボロール",
    nameInci: "Bisabolol",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "カモミールに含まれるテルペン系アルコールで、穏やかな鎮静作用があります。",
    funFact: "ドイツカモミールの精油成分として発見されました。",
  },
  {
    id: "azulene",
    nameJa: "アズレン",
    nameInci: "Azulene",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "カモミールから得られる深い青色の鎮静成分です。",
    funFact: "その鮮やかな青色から「アズール（空色）」という名前が付いています。",
  },
  {
    id: "chamomilla-extract",
    nameJa: "カミツレ花エキス",
    nameInci: "Chamomilla Recutita Flower Extract",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "カモミールの花から得られるエキスで、鎮静・保湿作用があります。",
    funFact: "ハーブティーとしても有名なカモミールは数千年の使用歴史があります。",
  },
  {
    id: "green-tea-extract",
    nameJa: "チャ葉エキス",
    nameInci: "Camellia Sinensis Leaf Extract",
    categories: ["soothing", "brightening"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "緑茶から得られるポリフェノール豊富なエキスで、鎮静・整肌作用があります。",
    funFact: "緑茶のカテキンは強い抗酸化作用を持つことで知られています。",
  },
  {
    id: "oat-extract",
    nameJa: "エンバクエキス",
    nameInci: "Avena Sativa Kernel Extract",
    categories: ["soothing", "moisturizing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "オートミールの原料であるエンバク（オーツ麦）から得られるエキスです。",
    funFact: "FDA（米国食品医薬品局）がスキンケア成分として認可したオート麦成分です。",
  },
  {
    id: "houttuynia-cordata-extract",
    nameJa: "ドクダミエキス",
    nameInci: "Houttuynia Cordata Extract",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "ドクダミから得られるエキスで、古くから民間療法で使われてきた鎮静成分です。",
    funFact: "日本の伝統的な薬草で「十薬」とも呼ばれています。",
  },
  {
    id: "caffeine",
    nameJa: "カフェイン",
    nameInci: "Caffeine",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "コーヒーや茶葉に含まれるアルカロイドで、スキンケアでは鎮静・引き締め目的で使われます。",
    funFact: "目の周りの浮腫を抑えるアイクリームに多く配合されています。",
  },

  // ─── 角質ケア系 ──────────────────────────────────────────
  {
    id: "salicylic-acid",
    nameJa: "サリチル酸",
    nameInci: "Salicylic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "BHA（β-ヒドロキシ酸）に分類される角質ケア成分です。",
    funFact: "ヤナギの樹皮から発見された歴史ある成分です。",
    caution: "濃度や使用頻度によっては刺激を感じる場合があります。",
  },
  {
    id: "glycolic-acid",
    nameJa: "グリコール酸",
    nameInci: "Glycolic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "AHA（α-ヒドロキシ酸）の中で最も分子が小さく、浸透性の高い角質ケア成分です。",
    funFact: "サトウキビから得られる天然由来の成分です。",
    caution: "使用後は紫外線対策をしっかり行うことが推奨されます。",
  },
  {
    id: "lactic-acid",
    nameJa: "乳酸",
    nameInci: "Lactic Acid",
    categories: ["keratin", "moisturizing"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "AHAの一種で、角質ケアと保湿の両面に作用する成分です。",
    funFact: "ヨーグルトや発酵乳製品に含まれる天然成分です。",
    caution: "AHA共通の注意として、使用後は日焼け対策が重要です。",
  },
  {
    id: "mandelic-acid",
    nameJa: "マンデル酸",
    nameInci: "Mandelic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "AHAの中で最も分子が大きく、比較的穏やかな角質ケア成分です。",
    funFact: "苦扁桃（ビターアーモンド）から最初に得られました。",
  },
  {
    id: "gluconolactone",
    nameJa: "グルコノラクトン",
    nameInci: "Gluconolactone",
    categories: ["keratin", "moisturizing"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "PHA（ポリヒドロキシ酸）の一種で、AHAより穏やかな角質ケア・保湿成分です。",
    funFact: "AHAよりも分子が大きいため、刺激が少ないとされています。",
  },
  {
    id: "lactobionic-acid",
    nameJa: "ラクトビオン酸",
    nameInci: "Lactobionic Acid",
    categories: ["keratin", "moisturizing"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "PHA（ポリヒドロキシ酸）の一種で、保湿力の高い穏やかな角質ケア成分です。",
    funFact: "乳糖を酸化して得られる成分で、高い吸湿性を持ちます。",
  },
  {
    id: "citric-acid",
    nameJa: "クエン酸",
    nameInci: "Citric Acid",
    categories: ["keratin"],
    rarity: "common",
    color: "#90A4AE",
    note: "AHAの一種で、pH調整や軽い角質ケア目的で多くの化粧品に配合されます。",
    funFact: "レモンなどの柑橘類に多く含まれる有機酸です。",
  },
  {
    id: "malic-acid",
    nameJa: "リンゴ酸",
    nameInci: "Malic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "リンゴに多く含まれるAHAの一種で、穏やかな角質ケア効果があります。",
    funFact: "「リンゴ酸」の名前の通りリンゴから発見された成分です。",
  },

  // ─── 植物油・バリア強化 ───────────────────────────────────
  {
    id: "rosehip-oil",
    nameJa: "ローズヒップ油",
    nameInci: "Rosa Canina Fruit Oil",
    categories: ["barrier", "brightening"],
    rarity: "uncommon",
    color: "#81C784",
    note: "バラの実から得られるオイルで、脂肪酸とビタミンCを豊富に含みます。",
    funFact: "チリやアルゼンチンの先住民族が古くから傷の治療に使ってきた成分です。",
  },
  {
    id: "argan-oil",
    nameJa: "アルガニアスピノサ核油",
    nameInci: "Argania Spinosa Kernel Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "rare",
    color: "#81C784",
    note: "モロッコのアルガンの木の実から得られる「液体ゴールド」とも呼ばれるオイルです。",
    funFact: "アルガンの木はモロッコにしか生息せず、ユネスコの生物圏保護区に指定されています。",
  },
  {
    id: "olive-oil",
    nameJa: "オリーブ果実油",
    nameInci: "Olea Europaea Fruit Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    color: "#81C784",
    note: "地中海原産のオリーブから得られる植物油で、肌のバリア機能を助けます。",
    funFact: "食用・化粧用・医薬用として数千年の使用歴史があります。",
  },
  {
    id: "sunflower-seed-oil",
    nameJa: "ヒマワリ種子油",
    nameInci: "Helianthus Annuus Seed Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    color: "#81C784",
    note: "ひまわりの種子から得られる軽いテクスチャーの植物油です。",
    funFact: "リノール酸が豊富で肌のバリア機能のサポートに役立ちます。",
  },
  {
    id: "macadamia-oil",
    nameJa: "マカデミア種子油",
    nameInci: "Macadamia Integrifolia Seed Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "uncommon",
    color: "#81C784",
    note: "マカダミアナッツから得られる植物油で、パルミトレイン酸が豊富です。",
    funFact: "人の皮脂に含まれるパルミトレイン酸と組成が似ています。",
  },
  {
    id: "rice-bran-oil",
    nameJa: "コメヌカ油",
    nameInci: "Oryza Sativa Bran Oil",
    categories: ["barrier", "moisturizing"],
    rarity: "common",
    color: "#81C784",
    note: "米ぬかから得られる植物油で、γ-オリザノールなどの有用成分を含みます。",
    funFact: "日本古来より美容オイルとして使われてきた成分です。",
  },

  // ─── 防腐・基剤・乳化 ─────────────────────────────────────
  {
    id: "phenoxyethanol",
    nameJa: "フェノキシエタノール",
    nameInci: "Phenoxyethanol",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "防腐剤として広く使用される成分です。",
    funFact: "緑茶にも微量に含まれる天然由来の成分です。",
  },
  {
    id: "methylparaben",
    nameJa: "メチルパラベン",
    nameInci: "Methylparaben",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "最も一般的なパラベン系防腐剤で、低濃度での使用が認められています。",
    funFact: "ブルーベリーなどの果物にも微量に天然に含まれています。",
  },
  {
    id: "ethylparaben",
    nameJa: "エチルパラベン",
    nameInci: "Ethylparaben",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "パラベン系防腐剤の一種で、広く化粧品に使用されます。",
  },
  {
    id: "propylparaben",
    nameJa: "プロピルパラベン",
    nameInci: "Propylparaben",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "パラベン系防腐剤の一種で、メチルパラベンと組み合わせて使用されます。",
  },
  {
    id: "butylparaben",
    nameJa: "ブチルパラベン",
    nameInci: "Butylparaben",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "パラベン系防腐剤の一種で、油溶性が高い特徴があります。",
  },
  {
    id: "carbomer",
    nameJa: "カルボマー",
    nameInci: "Carbomer",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "増粘剤・ゲル化剤として使用される高分子成分です。",
    funFact: "少量で強力なゲルを形成できるため、様々な製品に使われます。",
  },
  {
    id: "xanthan-gum",
    nameJa: "キサンタンガム",
    nameInci: "Xanthan Gum",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "微生物が産生する天然の多糖類で、増粘・安定化剤として使われます。",
    funFact: "食品にも使われる安全性の高い増粘剤です。",
  },
  {
    id: "hydroxyethylcellulose",
    nameJa: "ヒドロキシエチルセルロース",
    nameInci: "Hydroxyethylcellulose",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "セルロース由来の増粘剤で、透明なジェルを作るのに適しています。",
    funFact: "植物由来のセルロースを化学修飾した天然系増粘剤です。",
  },
  {
    id: "hexanediol",
    nameJa: "1,2-ヘキサンジオール",
    nameInci: "1,2-Hexanediol",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "保湿と防腐補助の両方に使われるマルチ機能成分です。",
    funFact: "パラベンフリー処方で代替的に使用されることの多い成分です。",
  },
  {
    id: "caprylyl-glycol",
    nameJa: "カプリリルグリコール",
    nameInci: "Caprylyl Glycol",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "保湿と防腐補助の両機能を持つ成分で、1,2-ヘキサンジオールと組み合わせて使われます。",
  },
  {
    id: "ethylhexylglycerin",
    nameJa: "エチルヘキシルグリセリン",
    nameInci: "Ethylhexylglycerin",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#9CA3AF",
    note: "グリセリン誘導体の防腐補助・保湿成分です。",
    funFact: "天然由来の植物性グリセリンを原料とした成分です。",
  },
  {
    id: "disodium-edta",
    nameJa: "EDTA-2Na",
    nameInci: "Disodium EDTA",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "キレート剤として製品の安定性を高めるために配合されます。",
    funFact: "金属イオンを捕捉することで、製品の変色や防腐効果の低下を防ぎます。",
  },
  {
    id: "sodium-hydroxide",
    nameJa: "水酸化Na",
    nameInci: "Sodium Hydroxide",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "pH調整剤として微量に配合され、製品の酸性度を適切に保ちます。",
    funFact: "苛性ソーダとも呼ばれますが、化粧品ではpH調整のごく微量のみ使用されます。",
  },
  {
    id: "sodium-citrate",
    nameJa: "クエン酸Na",
    nameInci: "Sodium Citrate",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "pH調整・緩衝剤として使用される成分です。",
    funFact: "食品添加物としても広く使われる安全性の高い成分です。",
  },
  {
    id: "polysorbate-20",
    nameJa: "ポリソルベート20",
    nameInci: "Polysorbate 20",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "水溶性の乳化剤・可溶化剤として幅広く使用されます。",
    funFact: "食品にも使用される安全性の高い非イオン性界面活性剤です。",
  },
  {
    id: "cocamidopropyl-betaine",
    nameJa: "コカミドプロピルベタイン",
    nameInci: "Cocamidopropyl Betaine",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "ヤシ油由来の両性界面活性剤で、低刺激な洗浄成分として使われます。",
    funFact: "泡立ちを良くしながら洗い上がりの感触を改善する効果があります。",
  },

  // ─── UV成分 ──────────────────────────────────────────────
  {
    id: "ethylhexyl-methoxycinnamate",
    nameJa: "メトキシケイヒ酸エチルヘキシル",
    nameInci: "Ethylhexyl Methoxycinnamate",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "UVB（紫外線B波）を吸収する有機系紫外線吸収剤です。",
    funFact: "最も広く使用されている紫外線吸収剤の一つです。",
  },
  {
    id: "zinc-oxide",
    nameJa: "酸化亜鉛",
    nameInci: "Zinc Oxide",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "UVA・UVBを物理的に反射・散乱させる無機系紫外線散乱剤です。",
    funFact: "ノンケミカル（物理的紫外線防止剤）として敏感肌にも使われます。",
  },
  {
    id: "titanium-dioxide",
    nameJa: "酸化チタン",
    nameInci: "Titanium Dioxide",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "UVB・一部UVAを物理的に反射させる無機系紫外線散乱剤です。",
    funFact: "白色顔料としても幅広く使用されています。",
  },
  {
    id: "avobenzone",
    nameJa: "t-ブチルメトキシジベンゾイルメタン",
    nameInci: "Butyl Methoxydibenzoylmethane",
    categories: [],
    rarity: "uncommon",
    color: "#9CA3AF",
    note: "アボベンゾンとも呼ばれ、UVAを広範囲に吸収する紫外線吸収剤です。",
    funFact: "光に不安定な特性があるため、安定化剤と組み合わせて使われます。",
  },
  {
    id: "tinosorb-s",
    nameJa: "ビスエチルヘキシルオキシフェノールメトキシフェニルトリアジン",
    nameInci: "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine",
    categories: [],
    rarity: "rare",
    color: "#7C6AE8",
    note: "Tinosorb Sの名で知られる、UVAとUVBを幅広くカバーする次世代紫外線吸収剤です。",
    funFact: "欧州では承認されていますが、米国FDAではまだ審査中の成分です。",
  },

  // ─── バイオテク・発酵成分 ─────────────────────────────────
  {
    id: "galactomyces-ferment",
    nameJa: "ガラクトミセス培養液",
    nameInci: "Galactomyces Ferment Filtrate",
    categories: ["brightening", "moisturizing"],
    rarity: "rare",
    color: "#7C6AE8",
    note: "清酒酵母の一種を発酵させた培養液で、整肌・保湿効果があります。",
    funFact: "酒造りの杜氏さんの手が白くきれいなことから研究が始まった成分です。",
  },
  {
    id: "bifida-ferment-lysate",
    nameJa: "ビフィズス菌溶解質",
    nameInci: "Bifida Ferment Lysate",
    categories: ["barrier", "brightening"],
    rarity: "rare",
    color: "#7C6AE8",
    note: "ビフィズス菌を発酵・溶解して得られるバイオテクノロジー由来の成分です。",
    funFact: "腸に良いとされるビフィズス菌の成分が肌のバリア機能にも役立ちます。",
  },
  {
    id: "lactobacillus-ferment",
    nameJa: "乳酸桿菌発酵液",
    nameInci: "Lactobacillus Ferment",
    categories: ["soothing", "moisturizing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "乳酸菌を発酵させた液で、肌の常在菌バランスをサポートする成分です。",
    funFact: "プロバイオティクスコスメのブームとともに注目度が高まっています。",
  },

  // ─── 植物エキス ───────────────────────────────────────────
  {
    id: "rosa-damascena-water",
    nameJa: "ダマスクバラ花水",
    nameInci: "Rosa Damascena Flower Water",
    categories: ["soothing", "moisturizing"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "ダマスクローズの蒸留水で、香り豊かな保湿・鎮静成分です。",
    funFact: "ローズウォーターは数千年前のペルシャで初めて製造されたとされています。",
  },
  {
    id: "pomegranate-extract",
    nameJa: "ザクロ果実エキス",
    nameInci: "Punica Granatum Fruit Extract",
    categories: ["brightening", "soothing"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "ザクロから得られるポリフェノール豊富なエキスです。",
    funFact: "古代ギリシャ・ローマ時代から薬用植物として使われてきた歴史があります。",
  },
  {
    id: "licorice-extract",
    nameJa: "カンゾウ根エキス",
    nameInci: "Glycyrrhiza Glabra Root Extract",
    categories: ["brightening", "soothing"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "甘草の根から得られるエキスで、整肌・鎮静の両作用を持ちます。",
    funFact: "漢方でも広く使われる甘草は、スキンケアでも有効性が研究されています。",
  },
  {
    id: "noni-extract",
    nameJa: "ヤエヤマアオキ果実エキス",
    nameInci: "Morinda Citrifolia Fruit Extract",
    categories: ["brightening"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "ノニとも呼ばれる南国植物の果実から得られるエキスです。",
    funFact: "ポリネシアの伝統医学で「奇跡の植物」として使われてきました。",
  },
];

export function getIngredientById(id: string): Ingredient | undefined {
  return MASTER_INGREDIENTS.find(i => i.id === id);
}

export function getIngredientByName(nameJa: string): Ingredient | undefined {
  return MASTER_INGREDIENTS.find(i => i.nameJa === nameJa);
}
