import { Ingredient, RarityKey, RarityInfo } from "@/types";

export const RARITY: Record<RarityKey, RarityInfo> = {
  common:    { label: "コモン",       star: 1, color: "#9CA3AF", icon: "🫧" },
  uncommon:  { label: "アンコモン",   star: 2, color: "#2D9CDB", icon: "🧪" },
  rare:      { label: "レア",         star: 3, color: "#7C6AE8", icon: "🔮" },
  legendary: { label: "レジェンダリー", star: 4, color: "#F59E0B", icon: "💎" },
};

export const MASTER_INGREDIENTS: Ingredient[] = [
  {
    id: "niacinamide",
    nameJa: "ナイアシンアミド",
    nameInci: "Niacinamide",
    categories: ["brightening", "barrier", "moisturizing"],
    rarity: "common",
    color: "#CE93D8",
    note: "ビタミンB3の一種で、多くのスキンケア製品に配合される成分です。",
    funFact: "ビタミンB3は水溶性ビタミンで、体内で補酵素NADの前駆体として働きます。",
  },
  {
    id: "retinol",
    nameJa: "レチノール",
    nameInci: "Retinol",
    categories: ["turnover"],
    rarity: "rare",
    color: "#FFB74D",
    note: "ビタミンAの一種で、ハリ・弾力系に分類される成分です。",
    funFact: "レチノールは1909年に発見された最初のビタミンです。",
    caution: "光に不安定なため、夜間の使用が一般的です。使い始めは少量からが推奨されます。",
  },
  {
    id: "salicylic-acid",
    nameJa: "サリチル酸",
    nameInci: "Salicylic Acid",
    categories: ["keratin"],
    rarity: "uncommon",
    color: "#90A4AE",
    note: "BHA（β-ヒドロキシ酸）に分類される角質ケア成分です。",
    funFact: "ヤナギの樹皮から発見された歴史ある成分です。",
    caution: "濃度や使用頻度によっては刺激を感じる場合があります。",
  },
  {
    id: "sodium-hyaluronate",
    nameJa: "ヒアルロン酸Na",
    nameInci: "Sodium Hyaluronate",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "高い保水力を持つ保湿成分として広く知られています。",
    funFact: "1gで約6リットルの水分を保持できると言われています。",
  },
  {
    id: "glycerin",
    nameJa: "グリセリン",
    nameInci: "Glycerin",
    categories: ["moisturizing"],
    rarity: "common",
    color: "#4FC3F7",
    note: "最も基本的な保湿成分の一つで、多くの化粧品に配合されています。",
    funFact: "食品にも使われる安全性の高い成分です。",
  },
  {
    id: "ascorbic-acid",
    nameJa: "アスコルビン酸",
    nameInci: "Ascorbic Acid",
    categories: ["brightening", "turnover"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "ビタミンCそのもので、整肌系・ハリ系に分類される成分です。",
    funFact: "壊血病の予防として発見された歴史があります。",
    caution: "酸化しやすいため、保存方法に注意が必要な成分です。",
  },
  {
    id: "ceramide-np",
    nameJa: "セラミドNP",
    nameInci: "Ceramide NP",
    categories: ["barrier", "moisturizing"],
    rarity: "rare",
    color: "#81C784",
    note: "肌のバリア機能に関わるセラミドの一種です。",
    funFact: "ヒトの角質層に存在する細胞間脂質の主成分です。",
  },
  {
    id: "phenoxyethanol",
    nameJa: "フェノキシエタノール",
    nameInci: "Phenoxyethanol",
    categories: [],
    rarity: "common",
    color: "#9CA3AF",
    note: "防腐剤として広く使用される成分です。",
    funFact: "緑茶にも微量に含まれる天然由来の成分です。",
  },
  {
    id: "tocopherol",
    nameJa: "トコフェロール",
    nameInci: "Tocopherol",
    categories: ["brightening"],
    rarity: "uncommon",
    color: "#CE93D8",
    note: "ビタミンEの一種で、整肌系に分類される成分です。",
    funFact: "「子供を産む」を意味するギリシャ語が名前の由来です。",
  },
  {
    id: "allantoin",
    nameJa: "アラントイン",
    nameInci: "Allantoin",
    categories: ["soothing"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "肌荒れ防止に分類される鎮静系の成分です。",
    funFact: "コンフリー（ヒレハリソウ）の根から発見された成分です。",
  },
  {
    id: "astaxanthin",
    nameJa: "アスタキサンチン",
    nameInci: "Astaxanthin",
    categories: ["brightening", "barrier"],
    rarity: "legendary",
    color: "#F59E0B",
    note: "カロテノイドの一種で、整肌・バリア系に分類される希少成分です。",
    funFact: "サケやエビの赤色の元となる天然色素です。",
  },
  {
    id: "cica",
    nameJa: "CICA",
    nameInci: "Centella Asiatica",
    categories: ["soothing", "barrier"],
    rarity: "uncommon",
    color: "#80CBC4",
    note: "ツボクサ由来の成分で、鎮静・バリア系に分類されます。",
    funFact: "韓国スキンケアブームで世界的に注目された成分です。",
  },
  {
    id: "bakuchiol",
    nameJa: "バクチオール",
    nameInci: "Bakuchiol",
    categories: ["turnover"],
    rarity: "rare",
    color: "#FFB74D",
    note: "植物由来のハリ・弾力系成分で、レチノールの代替として注目されています。",
    funFact: "インドの伝統医学アーユルヴェーダで古くから使われてきた植物由来です。",
  },
  {
    id: "peptide",
    nameJa: "ペプチド",
    nameInci: "Palmitoyl Tripeptide-1",
    categories: ["turnover", "barrier"],
    rarity: "legendary",
    color: "#F59E0B",
    note: "アミノ酸が結合した成分で、ハリ・弾力系・バリア系に分類される希少成分です。",
    funFact: "ペプチドは「消化する」を意味するギリシャ語が語源です。",
  },
  {
    id: "arbutin",
    nameJa: "アルブチン",
    nameInci: "Arbutin",
    categories: ["brightening"],
    rarity: "rare",
    color: "#7C6AE8",
    note: "コケモモなどに含まれる整肌系の成分です。",
    funFact: "1989年に日本で医薬部外品の有効成分として承認されました。",
  },
];

export function getIngredientById(id: string): Ingredient | undefined {
  return MASTER_INGREDIENTS.find(i => i.id === id);
}

export function getIngredientByName(nameJa: string): Ingredient | undefined {
  return MASTER_INGREDIENTS.find(i => i.nameJa === nameJa);
}
