# -*- coding: utf-8 -*-
"""Generate TypeScript entries for the 23 new ingredients."""
import sys
sys.stdout.reconfigure(encoding="utf-8")

NEW_INGREDIENTS = [
    {
        "nameJa": "アセチルヒアルロン酸Na",
        "id": "acetyl-hyaluronate",
        "nameInci": "Sodium Acetylhyaluronate",
        "genre": "water",
        "rarity": "rare",
        "color": "#4FC3F7",
        "categories": ["moisturizing", "turnover"],
        "note": "肌なじみのよいうるおい感を出しやすく、乾燥によるつっぱり感を和らげやすい。",
    },
    {
        "nameJa": "コロイド性オートミール",
        "id": "colloidal-oatmeal",
        "nameInci": "Avena Sativa (Oat) Kernel Flour",
        "genre": "botanical",
        "rarity": "uncommon",
        "color": "#E8D5B7",
        "categories": ["soothing", "moisturizing"],
        "note": "肌荒れ・かゆみ感を落ち着かせ、バリアをサポートする整肌成分。",
    },
    {
        "nameJa": "アロエベラ葉エキス",
        "id": "aloe-vera-leaf-extract",
        "nameInci": "Aloe Barbadensis Leaf Extract",
        "genre": "botanical",
        "rarity": "common",
        "color": "#66BB6A",
        "categories": ["soothing", "moisturizing"],
        "note": "整肌・保湿にはたらく植物エキスで、日焼け後のクールダウンにも使われやすい。",
    },
    {
        "nameJa": "カレンデュラ花エキス",
        "id": "calendula-flower-extract",
        "nameInci": "Calendula Officinalis Flower Extract",
        "genre": "botanical",
        "rarity": "uncommon",
        "color": "#FFB74D",
        "categories": ["soothing", "moisturizing"],
        "note": "肌をおだやかに整え、うるおいを守るマリーゴールド由来の成分。",
    },
    {
        "nameJa": "パルミチン酸アスコルビルリン酸3Na",
        "id": "trisodium-ascorbyl-palmitate-phosphate",
        "nameInci": "Trisodium Ascorbyl Palmitate Phosphate",
        "genre": "vitamin",
        "rarity": "rare",
        "color": "#FFA726",
        "categories": ["brightening", "turnover"],
        "note": "安定性と浸透感を両立したビタミンC誘導体で、整肌・透明感ケアに使われやすい。",
        "aliases": ["APPS", "アプレシエ"],
    },
    {
        "nameJa": "トコフェロール酢酸エステル",
        "id": "tocopheryl-acetate",
        "nameInci": "Tocopheryl Acetate",
        "genre": "vitamin",
        "rarity": "common",
        "color": "#FFD54F",
        "categories": ["turnover", "soothing"],
        "note": "安定性の高いビタミンE誘導体で、肌荒れ防止・抗酸化の補助として広く使われる。",
        "aliases": ["酢酸トコフェロール", "ビタミンE誘導体"],
    },
    {
        "nameJa": "緑茶エキス",
        "id": "green-tea-extract",
        "nameInci": "Camellia Sinensis Leaf Extract",
        "genre": "botanical",
        "rarity": "common",
        "color": "#81C784",
        "categories": ["soothing", "turnover"],
        "note": "カテキンを含む抗酸化力の高い植物エキスで、整肌・肌荒れサポートに。",
        "aliases": ["チャ葉エキス", "カメリアシネンシス葉エキス"],
    },
    {
        "nameJa": "N-アセチルグルコサミン",
        "id": "n-acetyl-glucosamine",
        "nameInci": "N-Acetyl Glucosamine",
        "genre": "amino_acid",
        "rarity": "uncommon",
        "color": "#CE93D8",
        "categories": ["brightening", "moisturizing"],
        "note": "ヒアルロン酸の原料でもあり、保湿と透明感サポートの両面で注目される成分。",
    },
    {
        "nameJa": "レチノイン酸トコフェリル",
        "id": "tocopheryl-retinoate",
        "nameInci": "Tocopheryl Retinoate",
        "genre": "vitamin",
        "rarity": "rare",
        "color": "#FF8A65",
        "categories": ["turnover", "keratin"],
        "note": "レチノールとビタミンEのハイブリッド型で、比較的おだやかにハリ・整肌にはたらく。",
    },
    {
        "nameJa": "パルミトイルトリペプチド-1",
        "id": "palmitoyl-tripeptide-1",
        "nameInci": "Palmitoyl Tripeptide-1",
        "genre": "peptide",
        "rarity": "rare",
        "color": "#E91E8C",
        "categories": ["turnover"],
        "note": "コラーゲン産生をサポートし、ハリ・弾力感の維持を助けるペプチド。",
    },
    {
        "nameJa": "アセチルヘキサペプチド-8",
        "id": "acetyl-hexapeptide-8",
        "nameInci": "Acetyl Hexapeptide-8",
        "genre": "peptide",
        "rarity": "legendary",
        "color": "#E91E8C",
        "categories": ["turnover"],
        "note": "表情ジワケアの補助として知られるペプチドで、アルジルリンとも呼ばれる。",
        "aliases": ["アルジルリン", "アルジレリン"],
    },
    {
        "nameJa": "オリゴペプチド-1",
        "id": "oligopeptide-1",
        "nameInci": "Oligopeptide-1",
        "genre": "peptide",
        "rarity": "legendary",
        "color": "#E91E8C",
        "categories": ["turnover", "soothing"],
        "note": "EGF様ペプチドとして知られ、肌の再生力をサポートする高機能成分。",
        "aliases": ["EGF"],
    },
    {
        "nameJa": "アセチルテトラペプチド-5",
        "id": "acetyl-tetrapeptide-5",
        "nameInci": "Acetyl Tetrapeptide-5",
        "genre": "peptide",
        "rarity": "rare",
        "color": "#E91E8C",
        "categories": ["turnover", "moisturizing"],
        "note": "目元のむくみ感・ハリ感をサポートする目元ケア向けペプチド。",
        "aliases": ["アイセリル"],
    },
    {
        "nameJa": "カプリロイルサリチル酸",
        "id": "capryloyl-salicylic-acid",
        "nameInci": "Capryloyl Salicylic Acid",
        "genre": "acid",
        "rarity": "rare",
        "color": "#B0BEC5",
        "categories": ["keratin", "soothing"],
        "note": "LHAとも呼ばれ、サリチル酸より穏やかな角質ケアとして使いやすい。",
        "aliases": ["LHA", "リポヒドロキシ酸"],
    },
    {
        "nameJa": "硫黄",
        "id": "sulfur",
        "nameInci": "Sulfur",
        "genre": "base",
        "rarity": "uncommon",
        "color": "#FFF176",
        "categories": ["keratin", "soothing"],
        "note": "皮脂吸着・殺菌作用があり、ニキビケア製品に配合されることが多い。",
        "aliases": ["イオウ"],
    },
    {
        "nameJa": "亜鉛PCA",
        "id": "zinc-pca",
        "nameInci": "Zinc PCA",
        "genre": "base",
        "rarity": "uncommon",
        "color": "#90A4AE",
        "categories": ["keratin", "soothing"],
        "note": "皮脂バランスを整え、毛穴の目立ちを抑える皮脂ケア成分。",
        "aliases": ["PCA亜鉛"],
    },
    {
        "nameJa": "ティーツリー葉油",
        "id": "tea-tree-oil",
        "nameInci": "Melaleuca Alternifolia (Tea Tree) Leaf Oil",
        "genre": "botanical",
        "rarity": "common",
        "color": "#A5D6A7",
        "categories": ["soothing", "keratin"],
        "note": "清潔感のある香りで、ニキビケアの整肌サポートとして人気の精油。",
    },
    {
        "nameJa": "カオリン",
        "id": "kaolin",
        "nameInci": "Kaolin",
        "genre": "base",
        "rarity": "common",
        "color": "#EFEBE9",
        "categories": ["keratin"],
        "note": "皮脂や汚れを吸着するクレイ成分で、洗い流すパック・マスクに使われやすい。",
    },
    {
        "nameJa": "ベントナイト",
        "id": "bentonite",
        "nameInci": "Bentonite",
        "genre": "base",
        "rarity": "common",
        "color": "#D7CCC8",
        "categories": ["keratin"],
        "note": "吸着力の高いクレイ成分で、毛穴の皮脂ケア・クレンジングマスクに定番。",
    },
    {
        "nameJa": "トコフェロールニコチン酸エステル",
        "id": "tocopheryl-nicotinate",
        "nameInci": "Tocopheryl Nicotinate",
        "genre": "vitamin",
        "rarity": "uncommon",
        "color": "#FFB74D",
        "categories": ["turnover", "soothing"],
        "note": "ビタミンEとナイアシンの複合体で、血行促進・整肌をサポート。",
    },
    {
        "nameJa": "水溶性プロテオグリカン",
        "id": "water-soluble-proteoglycan",
        "nameInci": "Hydrolyzed Proteoglycan",
        "genre": "water",
        "rarity": "rare",
        "color": "#4FC3F7",
        "categories": ["moisturizing", "turnover"],
        "note": "ヒアルロン酸超えともいわれる保水力を持ち、ハリ感サポートにも注目の成分。",
        "aliases": ["プロテオグリカン"],
    },
    {
        "nameJa": "グリシルグリシン",
        "id": "glycyl-glycine",
        "nameInci": "Glycyl Glycine",
        "genre": "amino_acid",
        "rarity": "uncommon",
        "color": "#7986CB",
        "categories": ["keratin", "moisturizing"],
        "note": "毛穴の開き・キメの乱れにアプローチし、なめらかな肌に導くジペプチド。",
    },
    {
        "nameJa": "フェニルエチルレゾルシノール",
        "id": "phenylethyl-resorcinol",
        "nameInci": "Phenylethyl Resorcinol",
        "genre": "base",
        "rarity": "rare",
        "color": "#CE93D8",
        "categories": ["brightening"],
        "note": "高い透明感ケア効果が期待される成分で、次世代の美白ケア原料として注目。",
        "aliases": ["377", "シムホワイト377"],
    },
]

# Output as TypeScript
for ing in NEW_INGREDIENTS:
    cats = ", ".join(f'"{c}"' for c in ing["categories"])
    lines = [
        "  {",
        f'    id: "{ing["id"]}",',
        f'    nameJa: "{ing["nameJa"]}",',
        f'    nameInci: "{ing["nameInci"]}",',
        f"    categories: [{cats}],",
        f'    rarity: "{ing["rarity"]}",',
        f'    genre: "{ing["genre"]}",',
        f'    color: "{ing["color"]}",',
        f'    note: "{ing["note"]}",',
    ]
    if "aliases" in ing:
        als = ", ".join(f'"{a}"' for a in ing["aliases"])
        lines.append(f"    aliases: [{als}],")
    lines.append("    activeIngredient: true,")
    lines.append("  },")
    print("\n".join(lines))

print(f"\n// Total: {len(NEW_INGREDIENTS)} new ingredients")
