export const RAKUTEN_CARD_WIDTH_PX = 160;
export const RAKUTEN_CARD_IMAGE_HEIGHT_PX = 128;
export const RAKUTEN_CARD_GAP_PX = 8;
export const RAKUTEN_CARD_SCROLL_STEP_PX =
  RAKUTEN_CARD_WIDTH_PX + RAKUTEN_CARD_GAP_PX;
